


const pmseList = [
  {
    "registeredName": "AMAZON WEB SERVICES, INC.",
    "countryCode": "US",
    "currency": "USD",
    "email": "contact@aws.com",
    "phoneNumber": "+12062661000",
    "classification": "Cloud_IT_Infra",
    "mccCode": "7372",
    "organizationTin": "TIN-911234567",
    "merchantName": "AWS",
    "merchantCity": "Seattle",
    "merchantCountryCode": "US",
    "acquirerInstitutionId": "ACQ_AWS_US",
    "merchantId": "AWS_US_001",
    "merchantGroup": "Amazon Global"
  },
 {
   "registeredName": "GOOGLE ASIA PACIFIC PTE. LTD.",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@google.com.sg",
   "phoneNumber": "+6565218000",
   "classification": "Cloud_IT_Infra",
   "mccCode": "7311",
   "organizationTin": "TIN-200812345G",
   "merchantName": "Google APAC",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_GOOGLE_SG",
   "merchantId": "GOOGLE_SG_002",
   "merchantGroup": "Google Global"
 },
 {
   "registeredName": "GOOGLE IRELAND LIMITED",
   "countryCode": "IE",
   "currency": "EUR",
   "email": "contact@google.ie",
   "phoneNumber": "+35315431000",
   "classification": "Cloud_IT_Infra",
   "mccCode": "7311",
   "organizationTin": "TIN-IE6388047V",
   "merchantName": "Google Ireland",
   "merchantCity": "Dublin",
   "merchantCountryCode": "IE",
   "acquirerInstitutionId": "ACQ_GOOGLE_IE",
   "merchantId": "GOOGLE_IE_003",
   "merchantGroup": "Google Global"
 },
 {
   "registeredName": "GOOGLE LLC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@google.com",
   "phoneNumber": "+16502530000",
   "classification": "Cloud_IT_Infra",
   "mccCode": "7311",
   "organizationTin": "TIN-942898923",
   "merchantName": "Google",
   "merchantCity": "Mountain View",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_GOOGLE_US",
   "merchantId": "GOOGLE_US_004",
   "merchantGroup": "Google Global"
 },
 {
   "registeredName": "SPOTIFY AB",
   "countryCode": "SE",
   "currency": "SEK",
   "email": "contact@spotify.com",
   "phoneNumber": "+4684501400",
   "classification": "Streaming_Entertainment",
   "mccCode": "5815",
   "organizationTin": "TIN-5567037485",
   "merchantName": "Spotify",
   "merchantCity": "Stockholm",
   "merchantCountryCode": "SE",
   "acquirerInstitutionId": "ACQ_SPOTIFY_SE",
   "merchantId": "SPOTIFY_SE_005",
   "merchantGroup": "Spotify"
 },
 {
   "registeredName": "APPLE DISTRIBUTION INTERNATIONAL LIMITED",
   "countryCode": "IE",
   "currency": "EUR",
   "email": "contact@apple.ie",
   "phoneNumber": "+353214283800",
   "classification": "EComm_Marketplaces",
   "mccCode": "5734",
   "organizationTin": "TIN-IE6369312T",
   "merchantName": "Apple Ireland",
   "merchantCity": "Cork",
   "merchantCountryCode": "IE",
   "acquirerInstitutionId": "ACQ_APPLE_IE",
   "merchantId": "APPLE_IE_006",
   "merchantGroup": "Apple Inc."
 },
 {
   "registeredName": "TIKTOK PTE. LTD.",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@tiktok.com",
   "phoneNumber": "+6567389595",
   "classification": "MEDIA_AND_ENTERTAINMENT",
   "mccCode": "4899",
   "organizationTin": "TIN-201815802K",
   "merchantName": "TikTok",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_TIKTOK_SG",
   "merchantId": "TIKTOK_SG_007",
   "merchantGroup": "ByteDance"
 },
 {
   "registeredName": "THE WALT DISNEY COMPANY (SOUTHEAST ASIA) PTE. LIMITED",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact.sea@disney.com",
   "phoneNumber": "+6565106868",
   "classification": "Streaming_Entertainment",
   "mccCode": "5815",
   "organizationTin": "TIN-199202511H",
   "merchantName": "Disney+ SEA",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_DISNEY_SG",
   "merchantId": "DISNEY_SG_008",
   "merchantGroup": "The Walt Disney Company"
 },
 {
   "registeredName": "AMAZON.COM SERVICES LLC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@amazon.com",
   "phoneNumber": "+12062661000",
   "classification": "EComm_Marketplaces",
   "mccCode": "5311",
   "organizationTin": "TIN-202302192",
   "merchantName": "Amazon.com",
   "merchantCity": "Seattle",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_AMAZON_US",
   "merchantId": "AMAZON_US_009",
   "merchantGroup": "Amazon Global"
 },
 {
   "registeredName": "AUDIBLE, INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@audible.com",
   "phoneNumber": "+18882835051",
   "classification": "Streaming_Entertainment",
   "mccCode": "5968",
   "organizationTin": "TIN-134015622",
   "merchantName": "Audible",
   "merchantCity": "Newark",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_AUDIBLE_US",
   "merchantId": "AUDIBLE_US_010",
   "merchantGroup": "Amazon Global"
 },
 {
   "registeredName": "ALEXA INTERNET",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@alexa.com",
   "phoneNumber": "+14157010424",
   "classification": "Streaming_Entertainment",
   "mccCode": "8999",
   "organizationTin": "TIN-943208461",
   "merchantName": "Alexa",
   "merchantCity": "San Francisco",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_ALEXA_US",
   "merchantId": "ALEXA_US_011",
   "merchantGroup": "Amazon Global"
 },
 {
   "registeredName": "AUDIBLE LIMITED",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact@audible.co.uk",
   "phoneNumber": "+442033580590",
   "classification": "Streaming_Entertainment",
   "mccCode": "5968",
   "organizationTin": "TIN-GB7 Audible",
   "merchantName": "Audible UK",
   "merchantCity": "London",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_AUDIBLE_GB",
   "merchantId": "AUDIBLE_GB_012",
   "merchantGroup": "Amazon Global"
 },
 {
   "registeredName": "META PLATFORMS IRELAND LIMITED",
   "countryCode": "IE",
   "currency": "EUR",
   "email": "contact@meta.ie",
   "phoneNumber": "+35316535000",
   "classification": "SocMed_Comm",
   "mccCode": "7375",
   "organizationTin": "TIN-IE9692928F",
   "merchantName": "Meta Ireland",
   "merchantCity": "Dublin",
   "merchantCountryCode": "IE",
   "acquirerInstitutionId": "ACQ_META_IE",
   "merchantId": "META_IE_013",
   "merchantGroup": "Meta Platforms"
 },
 {
   "registeredName": "META PLATFORMS TECHNOLOGIES IRELAND LIMITED",
   "countryCode": "IE",
   "currency": "EUR",
   "email": "contact.tech@meta.ie",
   "phoneNumber": "+35316535000",
   "classification": "SocMed_Comm",
   "mccCode": "4816",
   "organizationTin": "TIN-IE3464149KH",
   "merchantName": "Meta Tech IE",
   "merchantCity": "Dublin",
   "merchantCountryCode": "IE",
   "acquirerInstitutionId": "ACQ_METATEC_IE",
   "merchantId": "METATEC_IE_014",
   "merchantGroup": "Meta Platforms"
 },
 {
   "registeredName": "FACEBOOK TECHNOLOGIES INTERNATIONAL LIMITED",
   "countryCode": "IE",
   "currency": "EUR",
   "email": "contact.fb@meta.ie",
   "phoneNumber": "+35316535000",
   "classification": "SocMed_Comm",
   "mccCode": "4816",
   "organizationTin": "TIN-IE3464149KH",
   "merchantName": "Facebook Tech",
   "merchantCity": "Dublin",
   "merchantCountryCode": "IE",
   "acquirerInstitutionId": "ACQ_FBTEC_IE",
   "merchantId": "FBTEC_IE_015",
   "merchantGroup": "Meta Platforms"
 },
 {
   "registeredName": "PCCW VUCLIP (SINGAPORE) PTE. LTD.",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@vuclip.com",
   "phoneNumber": "+6568261188",
   "classification": "Streaming_Entertainment",
   "mccCode": "5815",
   "organizationTin": "TIN-201503732H",
   "merchantName": "Vuclip",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_VUCLIP_SG",
   "merchantId": "VUCLIP_SG_016",
   "merchantGroup": "PCCW"
 },
 {
   "registeredName": "SKYPE COMMUNICATIONS SARL",
   "countryCode": "LU",
   "currency": "EUR",
   "email": "contact@skype.lu",
   "phoneNumber": "+35226639140",
   "classification": "SocMed_Comm",
   "mccCode": "4814",
   "organizationTin": "TIN-LU20981643",
   "merchantName": "Skype",
   "merchantCity": "Luxembourg",
   "merchantCountryCode": "LU",
   "acquirerInstitutionId": "ACQ_SKYPE_LU",
   "merchantId": "SKYPE_LU_017",
   "merchantGroup": "Microsoft"
 },
 {
   "registeredName": "MOJANG AB",
   "countryCode": "SE",
   "currency": "SEK",
   "email": "contact@mojang.com",
   "phoneNumber": "+46850001000",
   "classification": "Streaming_Entertainment",
   "mccCode": "5816",
   "organizationTin": "TIN-5568192347",
   "merchantName": "Mojang",
   "merchantCity": "Stockholm",
   "merchantCountryCode": "SE",
   "acquirerInstitutionId": "ACQ_MOJANG_SE",
   "merchantId": "MOJANG_SE_018",
   "merchantGroup": "Microsoft"
 },
 {
   "registeredName": "LINKEDIN SINGAPORE PTE. LTD.",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@linkedin.sg",
   "phoneNumber": "+6566225500",
   "classification": "SocMed_Comm",
   "mccCode": "8999",
   "organizationTin": "TIN-201106827E",
   "merchantName": "LinkedIn SG",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_LINKEDIN_SG",
   "merchantId": "LINKEDIN_SG_019",
   "merchantGroup": "Microsoft"
 },
 {
   "registeredName": "MICROSOFT IRELAND OPERATIONS LIMITED",
   "countryCode": "IE",
   "currency": "EUR",
   "email": "contact@microsoft.ie",
   "phoneNumber": "+35312953826",
   "classification": "Cloud_IT_Infra",
   "mccCode": "5817",
   "organizationTin": "TIN-IE8256796U",
   "merchantName": "Microsoft IE",
   "merchantCity": "Dublin",
   "merchantCountryCode": "IE",
   "acquirerInstitutionId": "ACQ_MSFT_IE",
   "merchantId": "MSFT_IE_020",
   "merchantGroup": "Microsoft"
 },
 {
   "registeredName": "TWITTER ASIA PACIFIC PTE. LTD.",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@twitter.sg",
   "phoneNumber": "+6568008800",
   "classification": "SocMed_Comm",
   "mccCode": "7375",
   "organizationTin": "TIN-201314337H",
   "merchantName": "X (Twitter) APAC",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_X_SG",
   "merchantId": "X_SG_021",
   "merchantGroup": "X Corp."
 },
 {
   "registeredName": "TWITTER INTERNATIONAL COMPANY",
   "countryCode": "IE",
   "currency": "EUR",
   "email": "contact@twitter.ie",
   "phoneNumber": "+35316535000",
   "classification": "SocMed_Comm",
   "mccCode": "7375",
   "organizationTin": "TIN-IE9744031T",
   "merchantName": "X (Twitter) Intl",
   "merchantCity": "Dublin",
   "merchantCountryCode": "IE",
   "acquirerInstitutionId": "ACQ_X_IE",
   "merchantId": "X_IE_022",
   "merchantGroup": "X Corp."
 },
 {
   "registeredName": "ZOOM VIDEO COMMUNICATIONS, INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@zoom.us",
   "phoneNumber": "+18887999666",
   "classification": "Productivity_SaaS",
   "mccCode": "4814",
   "organizationTin": "TIN-454157969",
   "merchantName": "Zoom",
   "merchantCity": "San Jose",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_ZOOM_US",
   "merchantId": "ZOOM_US_023",
   "merchantGroup": "Zoom"
 },
 {
   "registeredName": "MCAFEE IRELAND LTD.",
   "countryCode": "IE",
   "currency": "EUR",
   "email": "contact@mcafee.ie",
   "phoneNumber": "+353214941100",
   "classification": "Security_VPN_Privacy",
   "mccCode": "5817",
   "organizationTin": "TIN-IE6380597O",
   "merchantName": "McAfee Ireland",
   "merchantCity": "Cork",
   "merchantCountryCode": "IE",
   "acquirerInstitutionId": "ACQ_MCAFEE_IE",
   "merchantId": "MCAFEE_IE_024",
   "merchantGroup": "McAfee"
 },
 {
   "registeredName": "PT JINGDONG INDONESIA PERTAMA",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@jd.id",
   "phoneNumber": "+622180627000",
   "classification": "EComm_Marketplaces",
   "mccCode": "5311",
   "organizationTin": "TIN-747683492023000",
   "merchantName": "JD.ID",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_JDID_SG",
   "merchantId": "JDID_SG_025",
   "merchantGroup": "JD.com"
 },
 {
   "registeredName": "PT SHOPEE INTERNATIONAL INDONESIA",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@shopee.co.id",
   "phoneNumber": "+622139500300",
   "classification": "EComm_Marketplaces",
   "mccCode": "5311",
   "organizationTin": "TIN-748363711021000",
   "merchantName": "Shopee",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_SHOPEE_SG",
   "merchantId": "SHOPEE_SG_026",
   "merchantGroup": "Sea Group"
 },
 {
   "registeredName": "NOVI DIGITAL ENTERTAINMENT PRIVATE LIMITED",
   "countryCode": "IN",
   "currency": "INR",
   "email": "contact@hotstar.com",
   "phoneNumber": "+912261967575",
   "classification": "Streaming_Entertainment",
   "mccCode": "5815",
   "organizationTin": "TIN-U72900MH200 Novi",
   "merchantName": "Hotstar",
   "merchantCity": "Mumbai",
   "merchantCountryCode": "IN",
   "acquirerInstitutionId": "ACQ_HOTSTAR_IN",
   "merchantId": "HOTSTAR_IN_027",
   "merchantGroup": "Disney"
 },
 {
   "registeredName": "ALIBABA CLOUD (SINGAPORE) PRIVATE LIMITED",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@alibabacloud.sg",
   "phoneNumber": "+6568095130",
   "classification": "Cloud_IT_Infra",
   "mccCode": "7372",
   "organizationTin": "TIN-201501589D",
   "merchantName": "Alibaba Cloud SG",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_ALIBB_SG",
   "merchantId": "ALIBB_SG_028",
   "merchantGroup": "Alibaba Group"
 },
 {
   "registeredName": "GITHUB, INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@github.com",
   "phoneNumber": "+18774484820",
   "classification": "Productivity_SaaS",
   "mccCode": "5817",
   "organizationTin": "TIN-260522140",
   "merchantName": "GitHub",
   "merchantCity": "San Francisco",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_GITHUB_US",
   "merchantId": "GITHUB_US_029",
   "merchantGroup": "Microsoft"
 },
 {
   "registeredName": "MICROSOFT CORPORATION",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@microsoft.com",
   "phoneNumber": "+14258828080",
   "classification": "Cloud_IT_Infra",
   "mccCode": "5817",
   "organizationTin": "TIN-911221191",
   "merchantName": "Microsoft",
   "merchantCity": "Redmond",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_MSFT_US",
   "merchantId": "MSFT_US_030",
   "merchantGroup": "Microsoft"
 },
 {
   "registeredName": "MICROSOFT REGIONAL SALES PTE. LTD.",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact.sg@microsoft.com",
   "phoneNumber": "+6568888899",
   "classification": "Cloud_IT_Infra",
   "mccCode": "5817",
   "organizationTin": "TIN-199204303Z",
   "merchantName": "Microsoft SG",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_MSFT_SG",
   "merchantId": "MSFT_SG_031",
   "merchantGroup": "Microsoft"
 },
 {
   "registeredName": "UCWEB SINGAPORE PTE. LTD.",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@ucweb.com",
   "phoneNumber": "+6568095130",
   "classification": "Streaming_Entertainment",
   "mccCode": "5817",
   "organizationTin": "TIN-201018312D",
   "merchantName": "UCWeb",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_UCWEB_SG",
   "merchantId": "UCWEB_SG_032",
   "merchantGroup": "Alibaba Group"
 },
 {
   "registeredName": "TO THE NEW PRIVATE LIMITED",
   "countryCode": "IN",
   "currency": "INR",
   "email": "contact@tothenew.com",
   "phoneNumber": "+911204043000",
   "classification": "Cloud_IT_Infra",
   "mccCode": "7379",
   "organizationTin": "TIN-U72200DL2 ToTheNew",
   "merchantName": "To The New",
   "merchantCity": "Noida",
   "merchantCountryCode": "IN",
   "acquirerInstitutionId": "ACQ_TTN_IN",
   "merchantId": "TTN_IN_033",
   "merchantGroup": "To The New"
 },
 {
   "registeredName": "CODA PAYMENTS PTE. LTD.",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@codapayments.com",
   "phoneNumber": "+6531583305",
   "classification": "Financial_Payments",
   "mccCode": "6012",
   "organizationTin": "TIN-201135258R",
   "merchantName": "Coda Payments",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_CODA_SG",
   "merchantId": "CODA_SG_034",
   "merchantGroup": "Coda"
 },
 {
   "registeredName": "NEXMO INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@vonage.com",
   "phoneNumber": "+18448262434",
   "classification": "Financial_Payments",
   "mccCode": "4814",
   "organizationTin": "TIN-453724810",
   "merchantName": "Nexmo (Vonage)",
   "merchantCity": "Holmdel",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_NEXMO_US",
   "merchantId": "NEXMO_US_035",
   "merchantGroup": "Vonage"
 },
 {
   "registeredName": "CLEVERBRIDGE AG",
   "countryCode": "DE",
   "currency": "EUR",
   "email": "contact@cleverbridge.com",
   "phoneNumber": "+49221222450",
   "classification": "Productivity_SaaS",
   "mccCode": "5311",
   "organizationTin": "TIN-DE814522896",
   "merchantName": "Cleverbridge",
   "merchantCity": "Cologne",
   "merchantCountryCode": "DE",
   "acquirerInstitutionId": "ACQ_CLEVER_DE",
   "merchantId": "CLEVER_DE_036",
   "merchantGroup": "Cleverbridge"
 },
 {
   "registeredName": "HEWLETT PACKARD ENTERPRISE COMPANY",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@hpe.com",
   "phoneNumber": "+16782593900",
   "classification": "Cloud_IT_Infra",
   "mccCode": "5045",
   "organizationTin": "TIN-472066016",
   "merchantName": "HPE",
   "merchantCity": "Houston",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_HPE_US",
   "merchantId": "HPE_US_037",
   "merchantGroup": "HPE"
 },
 {
   "registeredName": "IBM CLOUD INTERNATIONAL B.V.",
   "countryCode": "NL",
   "currency": "EUR",
   "email": "contact@softlayer.com",
   "phoneNumber": "+31207937793",
   "classification": "Cloud_IT_Infra",
   "mccCode": "7372",
   "organizationTin": "TIN-NL855320516B01",
   "merchantName": "IBM Cloud NL",
   "merchantCity": "Amsterdam",
   "merchantCountryCode": "NL",
   "acquirerInstitutionId": "ACQ_IBM_NL",
   "merchantId": "IBM_NL_038",
   "merchantGroup": "IBM"
 },
 {
   "registeredName": "PT BUKALAPAK.COM",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@bukalapak.com",
   "phoneNumber": "+622150813333",
   "classification": "EComm_Marketplaces",
   "mccCode": "5311",
   "organizationTin": "TIN-311617122022000",
   "merchantName": "Bukalapak",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_BLPK_SG",
   "merchantId": "BLPK_SG_039",
   "merchantGroup": "Bukalapak"
 },
 {
   "registeredName": "PT ECART WEBPORTAL INDONESIA",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@lazada.co.id",
   "phoneNumber": "+622180630200",
   "classification": "EComm_Marketplaces",
   "mccCode": "5311",
   "organizationTin": "TIN-315127025092000",
   "merchantName": "Lazada",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_LAZADA_SG",
   "merchantId": "LAZADA_SG_040",
   "merchantGroup": "Alibaba Group"
 },
 {
   "registeredName": "PT TOKOPEDIA",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@tokopedia.com",
   "phoneNumber": "+622150917000",
   "classification": "EComm_Marketplaces",
   "mccCode": "5311",
   "organizationTin": "TIN-029584674092000",
   "merchantName": "Tokopedia",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_TKPD_SG",
   "merchantId": "TKPD_SG_041",
   "merchantGroup": "GoTo"
 },
 {
   "registeredName": "PT GLOBAL DIGITAL NIAGA",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@blibli.com",
   "phoneNumber": "+6562125556060",
   "classification": "EComm_Marketplaces",
   "mccCode": "5311",
   "organizationTin": "TIN-311910294091000",
   "merchantName": "Blibli",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_BLIBLI_SG",
   "merchantId": "BLIBLI_SG_042",
   "merchantGroup": "Djarum"
 },
 {
   "registeredName": "VALVE CORPORATION",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@valvesoftware.com",
   "phoneNumber": "+14258899642",
   "classification": "Streaming_Entertainment",
   "mccCode": "5816",
   "organizationTin": "TIN-911733633",
   "merchantName": "Valve (Steam)",
   "merchantCity": "Bellevue",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_VALVE_US",
   "merchantId": "VALVE_US_043",
   "merchantGroup": "Valve"
 },
 {
   "registeredName": "BEIN SPORTS ASIA PTE LIMITED",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@beinsports.com",
   "phoneNumber": "+6564388300",
   "classification": "Streaming_Entertainment",
   "mccCode": "5815",
   "organizationTin": "TIN-201314923K",
   "merchantName": "beIN SPORTS",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_BEIN_SG",
   "merchantId": "BEIN_SG_044",
   "merchantGroup": "beIN Media"
 },
 {
   "registeredName": "ETSY IRELAND UNLIMITED COMPANY",
   "countryCode": "IE",
   "currency": "EUR",
   "email": "contact@etsy.com",
   "phoneNumber": "+35315133600",
   "classification": "EComm_Marketplaces",
   "mccCode": "5311",
   "organizationTin": "TIN-IE9753238G",
   "merchantName": "Etsy Ireland",
   "merchantCity": "Dublin",
   "merchantCountryCode": "IE",
   "acquirerInstitutionId": "ACQ_ETSY_IE",
   "merchantId": "ETSY_IE_045",
   "merchantGroup": "Etsy"
 },
 {
   "registeredName": "TENCENT MOBILE INTERNATIONAL LIMITED",
   "countryCode": "HK",
   "currency": "HKD",
   "email": "contact@tencent.com",
   "phoneNumber": "+85231485100",
   "classification": "Streaming_Entertainment",
   "mccCode": "5816",
   "organizationTin": "TIN-HK Tencent",
   "merchantName": "Tencent Games",
   "merchantCity": "Hong Kong",
   "merchantCountryCode": "HK",
   "acquirerInstitutionId": "ACQ_TENCENT_HK",
   "merchantId": "TENCENT_HK_047",
   "merchantGroup": "Tencent"
 },
 {
   "registeredName": "SNAP GROUP LIMITED",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact@snap.com",
   "phoneNumber": "+442038703200",
   "classification": "SocMed_Comm",
   "mccCode": "7375",
   "organizationTin": "TIN-GB Snap",
   "merchantName": "Snapchat",
   "merchantCity": "London",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_SNAP_GB",
   "merchantId": "SNAP_GB_048",
   "merchantGroup": "Snap Inc."
 },
 {
   "registeredName": "NORDVPN S.A.",
   "countryCode": "PA",
   "currency": "USD",
   "email": "contact@nordvpn.com",
   "phoneNumber": "+5078339478",
   "classification": "Security_VPN_Privacy",
   "mccCode": "5817",
   "organizationTin": "TIN-PA NordVPN",
   "merchantName": "NordVPN",
   "merchantCity": "Panama City",
   "merchantCountryCode": "PA",
   "acquirerInstitutionId": "ACQ_NORDVPN_PA",
   "merchantId": "NORDVPN_PA_049",
   "merchantGroup": "Nord Security"
 },
 {
   "registeredName": "EBAY MARKETPLACES GMBH",
   "countryCode": "DE",
   "currency": "EUR",
   "email": "contact@ebay.de",
   "phoneNumber": "+4933203851100",
   "classification": "EComm_Marketplaces",
   "mccCode": "5311",
   "organizationTin": "TIN-DE206775614",
   "merchantName": "eBay Germany",
   "merchantCity": "Kleinmachnow",
   "merchantCountryCode": "DE",
   "acquirerInstitutionId": "ACQ_EBAY_DE",
   "merchantId": "EBAY_DE_050",
   "merchantGroup": "eBay"
 },
 {
   "registeredName": "IMAGE FUTURE INVESTMENT (HK) LIMITED",
   "countryCode": "HK",
   "currency": "HKD",
   "email": "contact@imagefuture.hk",
   "phoneNumber": "+85212345678",
   "classification": "Other_Services",
   "mccCode": "6211",
   "organizationTin": "TIN-HK Image",
   "merchantName": "Image Future HK",
   "merchantCity": "Hong Kong",
   "merchantCountryCode": "HK",
   "acquirerInstitutionId": "ACQ_IMGINV_HK",
   "merchantId": "IMGINV_HK_051",
   "merchantGroup": "Image Future"
 },
 {
   "registeredName": "AMAZON.COM.CA, INC.",
   "countryCode": "CA",
   "currency": "CAD",
   "email": "contact@amazon.ca",
   "phoneNumber": "+18775863230",
   "classification": "EComm_Marketplaces",
   "mccCode": "5311",
   "organizationTin": "TIN-CA Amazon",
   "merchantName": "Amazon.ca",
   "merchantCity": "Toronto",
   "merchantCountryCode": "CA",
   "acquirerInstitutionId": "ACQ_AMZN_CA",
   "merchantId": "AMZN_CA_052",
   "merchantGroup": "Amazon Global"
 },
 {
   "registeredName": "DROPBOX INTERNATIONAL UNLIMITED COMPANY",
   "countryCode": "IE",
   "currency": "EUR",
   "email": "contact@dropbox.ie",
   "phoneNumber": "+35316535000",
   "classification": "Productivity_SaaS",
   "mccCode": "7372",
   "organizationTin": "TIN-IE3293991LH",
   "merchantName": "Dropbox Ireland",
   "merchantCity": "Dublin",
   "merchantCountryCode": "IE",
   "acquirerInstitutionId": "ACQ_DROPBOX_IE",
   "merchantId": "DROPBOX_IE_053",
   "merchantGroup": "Dropbox"
 },
 {
   "registeredName": "PT DUA PULUH EMPAT JAM ONLINE",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@24h.co.id",
   "phoneNumber": "+622129333000",
   "classification": "EComm_Marketplaces",
   "mccCode": "5994",
   "organizationTin": "TIN-314815234021000",
   "merchantName": "24h Online",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_24H_SG",
   "merchantId": "24H_SG_054",
   "merchantGroup": "24h Group"
 },
 {
   "registeredName": "NEXWAY SASU",
   "countryCode": "FR",
   "currency": "EUR",
   "email": "contact@nexway.com",
   "phoneNumber": "+33155171580",
   "classification": "Productivity_SaaS",
   "mccCode": "5311",
   "organizationTin": "TIN-FR42442750171",
   "merchantName": "Nexway",
   "merchantCity": "Paris",
   "merchantCountryCode": "FR",
   "acquirerInstitutionId": "ACQ_NEXWAY_FR",
   "merchantId": "NEXWAY_FR_055",
   "merchantGroup": "Nexway"
 },
 {
   "registeredName": "BRIGHT MARKET LLC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@fastspring.com",
   "phoneNumber": "+18055635804",
   "classification": "Other_Services",
   "mccCode": "5311",
   "organizationTin": "TIN-205934522",
   "merchantName": "FastSpring",
   "merchantCity": "Santa Barbara",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_FSPR_US",
   "merchantId": "FSPR_US_056",
   "merchantGroup": "FastSpring"
 },
 {
   "registeredName": "PT FASHION MARKETPLACE INDONESIA",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@zalora.co.id",
   "phoneNumber": "+622129490100",
   "classification": "EComm_Marketplaces",
   "mccCode": "5699",
   "organizationTin": "TIN-316209867021000",
   "merchantName": "Zalora",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_ZALORA_SG",
   "merchantId": "ZALORA_SG_057",
   "merchantGroup": "Global Fashion"
 },
 {
   "registeredName": "BOLD LLC",
   "countryCode": "PR",
   "currency": "USD",
   "email": "contact@bold.com",
   "phoneNumber": "+18443517441",
   "classification": "Other_Services",
   "mccCode": "8999",
   "organizationTin": "TIN-PR BOLD",
   "merchantName": "Bold",
   "merchantCity": "Guaynabo",
   "merchantCountryCode": "PR",
   "acquirerInstitutionId": "ACQ_BOLD_PR",
   "merchantId": "BOLD_PR_058",
   "merchantGroup": "Bold"
 },
 {
   "registeredName": "HIGH MORALE DEVELOPMENTS LIMITED.",
   "countryCode": "CY",
   "currency": "EUR",
   "email": "contact@hmdev.com",
   "phoneNumber": "+35722123456",
   "classification": "Other_Services",
   "mccCode": "5817",
   "organizationTin": "TIN-CY HMDev",
   "merchantName": "High Morale Dev",
   "merchantCity": "Nicosia",
   "merchantCountryCode": "CY",
   "acquirerInstitutionId": "ACQ_HMD_CY",
   "merchantId": "HMD_CY_059",
   "merchantGroup": "High Morale"
 },
 {
   "registeredName": "ACEVILLE PTE LTD.",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@aceville.sg",
   "phoneNumber": "+6512345678",
   "classification": "Other_Services",
   "mccCode": "5311",
   "organizationTin": "TIN-SG Aceville",
   "merchantName": "Aceville",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_ACEVIL_SG",
   "merchantId": "ACEVIL_SG_060",
   "merchantGroup": "Aceville Group"
 },
 {
   "registeredName": "WETRANSFER B.V",
   "countryCode": "NL",
   "currency": "EUR",
   "email": "contact@wetransfer.com",
   "phoneNumber": "+31202401140",
   "classification": "Productivity_SaaS",
   "mccCode": "7372",
   "organizationTin": "TIN-NL822453436B01",
   "merchantName": "WeTransfer",
   "merchantCity": "Amsterdam",
   "merchantCountryCode": "NL",
   "acquirerInstitutionId": "ACQ_WETR_NL",
   "merchantId": "WETR_NL_061",
   "merchantGroup": "WeTransfer"
 },
 {
   "registeredName": "CHEGG, INC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@chegg.com",
   "phoneNumber": "+14088555700",
   "classification": "EDUCATION",
   "mccCode": "8299",
   "organizationTin": "TIN-202275822",
   "merchantName": "Chegg",
   "merchantCity": "Santa Clara",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_CHEGG_US",
   "merchantId": "CHEGG_US_062",
   "merchantGroup": "Chegg"
 },
 {
   "registeredName": "BOOKING.COM B.V",
   "countryCode": "NL",
   "currency": "EUR",
   "email": "contact@booking.com",
   "phoneNumber": "+31707703884",
   "classification": "Travel_Hospitality",
   "mccCode": "4722",
   "organizationTin": "TIN-NL805734958B01",
   "merchantName": "Booking.com",
   "merchantCity": "Amsterdam",
   "merchantCountryCode": "NL",
   "acquirerInstitutionId": "ACQ_BOOKING_NL",
   "merchantId": "BOOKING_NL_063",
   "merchantGroup": "Booking"
 },
 {
   "registeredName": "EA SWISS SARL",
   "countryCode": "CH",
   "currency": "CHF",
   "email": "contact@ea.com",
   "phoneNumber": "+41223161300",
   "classification": "Streaming_Entertainment",
   "mccCode": "5816",
   "organizationTin": "TIN-CHE-112.531.025",
   "merchantName": "Electronic Arts",
   "merchantCity": "Geneva",
   "merchantCountryCode": "CH",
   "acquirerInstitutionId": "ACQ_EA_CH",
   "merchantId": "EA_CH_064",
   "merchantGroup": "EA"
 },
 {
   "registeredName": "ELSEVIER B.V",
   "countryCode": "NL",
   "currency": "EUR",
   "email": "contact@elsevier.com",
   "phoneNumber": "+31204853911",
   "classification": "Publishing_Media_News",
   "mccCode": "2741",
   "organizationTin": "TIN-NL005033019B01",
   "merchantName": "Elsevier",
   "merchantCity": "Amsterdam",
   "merchantCountryCode": "NL",
   "acquirerInstitutionId": "ACQ_ELSEV_NL",
   "merchantId": "ELSEV_NL_065",
   "merchantGroup": "RELX"
 },
 {
   "registeredName": "BLIZZARD ENTERTAINMENT INC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@blizzard.com",
   "phoneNumber": "+19499551380",
   "classification": "Streaming_Entertainment",
   "mccCode": "5816",
   "organizationTin": "TIN-954329245",
   "merchantName": "Blizzard",
   "merchantCity": "Irvine",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_BLIZZ_US",
   "merchantId": "BLIZZ_US_066",
   "merchantGroup": "Activision"
 },
 {
   "registeredName": "NEW YORK TIMES DIGITAL LLC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@nytimes.com",
   "phoneNumber": "+18006984637",
   "classification": "Publishing_Media_News",
   "mccCode": "5994",
   "organizationTin": "TIN-NYT Digital",
   "merchantName": "NYT Digital",
   "merchantCity": "New York",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_NYT_US",
   "merchantId": "NYT_US_067",
   "merchantGroup": "NYT"
 },
 {
   "registeredName": "CANVA PTY LTD",
   "countryCode": "AU",
   "currency": "AUD",
   "email": "contact@canva.com",
   "phoneNumber": "+61280687888",
   "classification": "Design_Creative_Stock_Media",
   "mccCode": "5817",
   "organizationTin": "TIN-AU Canva",
   "merchantName": "Canva",
   "merchantCity": "Sydney",
   "merchantCountryCode": "AU",
   "acquirerInstitutionId": "ACQ_CANVA_AU",
   "merchantId": "CANVA_AU_068",
   "merchantGroup": "Canva"
 },
 {
   "registeredName": "DEGREED INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@degreed.com",
   "phoneNumber": "+18005319580",
   "classification": "EdTech_Digi_Learn",
   "mccCode": "8299",
   "organizationTin": "TIN-455431613",
   "merchantName": "Degreed",
   "merchantCity": "Pleasanton",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_DEGREED_US",
   "merchantId": "DEGREED_US_069",
   "merchantGroup": "Degreed"
 },
 {
   "registeredName": "LNRS DATA SERVICES LIMITED",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact@lnrs.co.uk",
   "phoneNumber": "+442012345678",
   "classification": "Research_Data_Services",
   "mccCode": "8999",
   "organizationTin": "TIN-GB LNRS",
   "merchantName": "LNRS Data",
   "merchantCity": "London",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_LNRS_GB",
   "merchantId": "LNRS_GB_070",
   "merchantGroup": "LNRS"
 },
 {
   "registeredName": "LEXISNEXIS RISK SOLUTIONS FL INC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@lexisnexis.com",
   "phoneNumber": "+18008690751",
   "classification": "Productivity_SaaS",
   "mccCode": "8999",
   "organizationTin": "TIN-LexisNexis",
   "merchantName": "LexisNexis",
   "merchantCity": "Boca Raton",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_LEXIS_US",
   "merchantId": "LEXIS_US_071",
   "merchantGroup": "RELX"
 },
 {
   "registeredName": "SURFSHARK B.V.",
   "countryCode": "NL",
   "currency": "EUR",
   "email": "contact@surfshark.com",
   "phoneNumber": "+31201234567",
   "classification": "Security_VPN_Privacy",
   "mccCode": "5817",
   "organizationTin": "TIN-NL Surfshark",
   "merchantName": "Surfshark",
   "merchantCity": "Amsterdam",
   "merchantCountryCode": "NL",
   "acquirerInstitutionId": "ACQ_SURFS_NL",
   "merchantId": "SURFS_NL_072",
   "merchantGroup": "Nord Security"
 },
 {
   "registeredName": "TO THE NEW SINGAPORE PTE. LTD.",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact.sg@tothenew.com",
   "phoneNumber": "+6569116233",
   "classification": "Cloud_IT_Infra",
   "mccCode": "7379",
   "organizationTin": "TIN-201534015E",
   "merchantName": "To The New SG",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_TTN_SG",
   "merchantId": "TTN_SG_073",
   "merchantGroup": "To The New"
 },
 {
   "registeredName": "EZVIZ INTERNATIONAL LIMITED",
   "countryCode": "HK",
   "currency": "HKD",
   "email": "contact@ezviz.com",
   "phoneNumber": "+85226152333",
   "classification": "Streaming_Entertainment",
   "mccCode": "5045",
   "organizationTin": "TIN-HK EZVIZ",
   "merchantName": "EZVIZ",
   "merchantCity": "Hong Kong",
   "merchantCountryCode": "HK",
   "acquirerInstitutionId": "ACQ_EZVIZ_HK",
   "merchantId": "EZVIZ_HK_074",
   "merchantGroup": "Hikvision"
 },
 {
   "registeredName": "EVERNOTE GMBH",
   "countryCode": "CH",
   "currency": "CHF",
   "email": "contact@evernote.com",
   "phoneNumber": "+41445862211",
   "classification": "Productivity_SaaS",
   "mccCode": "5817",
   "organizationTin": "TIN-CHE-332.955.578",
   "merchantName": "Evernote",
   "merchantCity": "Zurich",
   "merchantCountryCode": "CH",
   "acquirerInstitutionId": "ACQ_EVNOTE_CH",
   "merchantId": "EVNOTE_CH_075",
   "merchantGroup": "Evernote"
 },
 {
   "registeredName": "ASANA, INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@asana.com",
   "phoneNumber": "+14155252323",
   "classification": "EdTech_Digi_Learn",
   "mccCode": "5817",
   "organizationTin": "TIN-264024419",
   "merchantName": "Asana",
   "merchantCity": "San Francisco",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_ASANA_US",
   "merchantId": "ASANA_US_076",
   "merchantGroup": "Asana"
 },
 {
   "registeredName": "CHANGE.ORG",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@change.org",
   "phoneNumber": "+14158821919",
   "classification": "SocMed_Comm",
   "mccCode": "8398",
   "organizationTin": "TIN-208620248",
   "merchantName": "Change.org",
   "merchantCity": "San Francisco",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_CHANGE_US",
   "merchantId": "CHANGE_US_078",
   "merchantGroup": "Change.org"
 },
 {
   "registeredName": "PT OCOMMERCE CAPITAL INDONESIA",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@ocommerce.id",
   "phoneNumber": "+622112345678",
   "classification": "EComm_Marketplaces",
   "mccCode": "6012",
   "organizationTin": "TIN-Ocommerce",
   "merchantName": "Ocommerce",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_OCOM_SG",
   "merchantId": "OCOM_SG_079",
   "merchantGroup": "Ocommerce"
 },
 {
   "registeredName": "CGTRADER UAB",
   "countryCode": "LT",
   "currency": "EUR",
   "email": "contact@cgtrader.com",
   "phoneNumber": "+37061234567",
   "classification": "Design_Creative_Stock_Media",
   "mccCode": "5311",
   "organizationTin": "TIN-LT CGTrader",
   "merchantName": "CGTrader",
   "merchantCity": "Vilnius",
   "merchantCountryCode": "LT",
   "acquirerInstitutionId": "ACQ_CGTRD_LT",
   "merchantId": "CGTRD_LT_080",
   "merchantGroup": "CGTrader"
 },
 {
   "registeredName": "ESET, SPOL, S R.O.",
   "countryCode": "SK",
   "currency": "EUR",
   "email": "contact@eset.com",
   "phoneNumber": "+421232244111",
   "classification": "Productivity_SaaS",
   "mccCode": "5817",
   "organizationTin": "TIN-SK ESET",
   "merchantName": "ESET",
   "merchantCity": "Bratislava",
   "merchantCountryCode": "SK",
   "acquirerInstitutionId": "ACQ_ESET_SK",
   "merchantId": "ESET_SK_081",
   "merchantGroup": "ESET"
 },
 {
   "registeredName": "TRADINGVIEW, INC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@tradingview.com",
   "phoneNumber": "+18001234567",
   "classification": "Productivity_SaaS",
   "mccCode": "6211",
   "organizationTin": "TIN-TradingView",
   "merchantName": "TradingView",
   "merchantCity": "New York",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_TRDVW_US",
   "merchantId": "TRDVW_US_082",
   "merchantGroup": "TradingView"
 },
 {
   "registeredName": "AMPLITUDE INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@amplitude.com",
   "phoneNumber": "+18882229242",
   "classification": "Productivity_SaaS",
   "mccCode": "5817",
   "organizationTin": "TIN-455431613",
   "merchantName": "Amplitude",
   "merchantCity": "San Francisco",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_AMPL_US",
   "merchantId": "AMPL_US_083",
   "merchantGroup": "Amplitude"
 },
 {
   "registeredName": "CAMBRIDGE UNIVERSITY PRESS and ASSESMENT UK",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact@cambridge.org",
   "phoneNumber": "+441223358331",
   "classification": "Publishing_Media_News",
   "mccCode": "2741",
   "organizationTin": "TIN-GB Cambridge",
   "merchantName": "Cambridge Press",
   "merchantCity": "Cambridge",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_CAMP_GB",
   "merchantId": "CAMP_GB_084",
   "merchantGroup": "Cambridge"
 },
 {
   "registeredName": "PREZI, INC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@prezi.com",
   "phoneNumber": "+18444677394",
   "classification": "Productivity_SaaS",
   "mccCode": "5817",
   "organizationTin": "TIN-270836371",
   "merchantName": "Prezi",
   "merchantCity": "San Francisco",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_PREZI_US",
   "merchantId": "PREZI_US_085",
   "merchantGroup": "Prezi"
 },
 {
   "registeredName": "GRAMMARLY, INC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@grammarly.com",
   "phoneNumber": "+18881234567",
   "classification": "Productivity_SaaS",
   "mccCode": "5817",
   "organizationTin": "TIN-Grammarly",
   "merchantName": "Grammarly",
   "merchantCity": "San Francisco",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_GRAMM_US",
   "merchantId": "GRAMM_US_087",
   "merchantGroup": "Grammarly"
 },
 {
   "registeredName": "SALESFORCE.COM SINGAPORE PTE LTD",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact.sg@salesforce.com",
   "phoneNumber": "+6563025700",
   "classification": "Productivity_SaaS",
   "mccCode": "5817",
   "organizationTin": "TIN-200502129G",
   "merchantName": "Salesforce SG",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_SLSFC_SG",
   "merchantId": "SLSFC_SG_088",
   "merchantGroup": "Salesforce"
 },
 {
   "registeredName": "NETFLIX PTE. LTD.",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@netflix.com.sg",
   "phoneNumber": "+6531584348",
   "classification": "Streaming_Entertainment",
   "mccCode": "5815",
   "organizationTin": "TIN-201531181K",
   "merchantName": "Netflix Singapore",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_NFLX_SG",
   "merchantId": "NFLX_SG_089",
   "merchantGroup": "Netflix Inc."
 },
 {
   "registeredName": "FREEPIK COMPANY S.L.",
   "countryCode": "ES",
   "currency": "EUR",
   "email": "contact@freepik.com",
   "phoneNumber": "+34951252107",
   "classification": "Design_Creative_Stock_Media",
   "mccCode": "5968",
   "organizationTin": "TIN-ES Freepik",
   "merchantName": "Freepik",
   "merchantCity": "Malaga",
   "merchantCountryCode": "ES",
   "acquirerInstitutionId": "ACQ_FREEP_ES",
   "merchantId": "FREEP_ES_090",
   "merchantGroup": "Freepik"
 },
 {
   "registeredName": "EXPEDIA LODGING PARTNER SERVICES SARL",
   "countryCode": "CH",
   "currency": "CHF",
   "email": "contact@expedia.ch",
   "phoneNumber": "+41225181136",
   "classification": "Travel_Hospitality",
   "mccCode": "4722",
   "organizationTin": "TIN-CH Expedia",
   "merchantName": "Expedia Lodging",
   "merchantCity": "Geneva",
   "merchantCountryCode": "CH",
   "acquirerInstitutionId": "ACQ_EXPED_CH",
   "merchantId": "EXPED_CH_091",
   "merchantGroup": "Expedia"
 },
 {
   "registeredName": "TRAVELSCAPE, LLC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@travelscape.com",
   "phoneNumber": "+17029392590",
   "classification": "Travel_Hospitality",
   "mccCode": "4722",
   "organizationTin": "TIN-Travelscape",
   "merchantName": "Travelscape",
   "merchantCity": "Las Vegas",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_TRVSC_US",
   "merchantId": "TRVSC_US_092",
   "merchantGroup": "Expedia"
 },
 {
   "registeredName": "TEAMVIEWER GERMANY GMBH",
   "countryCode": "DE",
   "currency": "EUR",
   "email": "contact@teamviewer.com",
   "phoneNumber": "+4971616069250",
   "classification": "Specialized_Software_Tools",
   "mccCode": "5817",
   "organizationTin": "TIN-DE257122502",
   "merchantName": "TeamViewer",
   "merchantCity": "Goppingen",
   "merchantCountryCode": "DE",
   "acquirerInstitutionId": "ACQ_TMVWR_DE",
   "merchantId": "TMVWR_DE_093",
   "merchantGroup": "TeamViewer"
 },
 {
   "registeredName": "SCRIBD, INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@scribd.com",
   "phoneNumber": "+18774672742",
   "classification": "Publishing_Media_News",
   "mccCode": "2741",
   "organizationTin": "TIN-208889490",
   "merchantName": "Scribd",
   "merchantCity": "San Francisco",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_SCRIBD_US",
   "merchantId": "SCRIBD_US_094",
   "merchantGroup": "Scribd"
 },
 {
   "registeredName": "TUNNELBEAR LLC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@tunnelbear.com",
   "phoneNumber": "+18558866357",
   "classification": "Security_VPN_Privacy",
   "mccCode": "5817",
   "organizationTin": "TIN-TunnelBear",
   "merchantName": "TunnelBear",
   "merchantCity": "Toronto",
   "merchantCountryCode": "CA",
   "acquirerInstitutionId": "ACQ_TNBR_CA",
   "merchantId": "TNBR_CA_095",
   "merchantGroup": "McAfee"
 },
 {
   "registeredName": "XSOLLA (USA), INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@xsolla.com",
   "phoneNumber": "+18184356613",
   "classification": "Gaming_Platforms_Distribution",
   "mccCode": "6012",
   "organizationTin": "TIN-Xsolla",
   "merchantName": "Xsolla",
   "merchantCity": "Sherman Oaks",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_XSOLLA_US",
   "merchantId": "XSOLLA_US_096",
   "merchantGroup": "Xsolla"
 },
 {
   "registeredName": "PADDLE.COM MARKET LIMITED",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact@paddle.com",
   "phoneNumber": "+442034326520",
   "classification": "Productivity_SaaS",
   "mccCode": "5311",
   "organizationTin": "TIN-GB Paddle",
   "merchantName": "Paddle",
   "merchantCity": "London",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_PADDLE_GB",
   "merchantId": "PADDLE_GB_097",
   "merchantGroup": "Paddle"
 },
 {
   "registeredName": "PLURALSIGHT, LLC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@pluralsight.com",
   "phoneNumber": "+18017849007",
   "classification": "Productivity_SaaS",
   "mccCode": "8299",
   "organizationTin": "TIN-Pluralsight",
   "merchantName": "Pluralsight",
   "merchantCity": "Draper",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_PLUR_US",
   "merchantId": "PLUR_US_098",
   "merchantGroup": "Pluralsight"
 },
 {
   "registeredName": "AUTOMATTIC INC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@automattic.com",
   "phoneNumber": "+18772733049",
   "classification": "Productivity_SaaS",
   "mccCode": "5817",
   "organizationTin": "TIN-20 Automattic",
   "merchantName": "Automattic",
   "merchantCity": "San Francisco",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_AUTO_US",
   "merchantId": "AUTO_US_099",
   "merchantGroup": "Automattic"
 },
 {
   "registeredName": "WOOCOMMERCE INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@woocommerce.com",
   "phoneNumber": "+18772733049",
   "classification": "E-commerce",
   "mccCode": "5311",
   "organizationTin": "TIN-WooCommerce",
   "merchantName": "WooCommerce",
   "merchantCity": "San Francisco",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_WOO_US",
   "merchantId": "WOO_US_100",
   "merchantGroup": "Automattic"
 },
 {
   "registeredName": "PIPEDRIVE OU",
   "countryCode": "EE",
   "currency": "EUR",
   "email": "contact@pipedrive.com",
   "phoneNumber": "+3726027000",
   "classification": "EdTech_Digi_Learn",
   "mccCode": "5817",
   "organizationTin": "TIN-EE Pipedrive",
   "merchantName": "Pipedrive",
   "merchantCity": "Tallinn",
   "merchantCountryCode": "EE",
   "acquirerInstitutionId": "ACQ_PIPE_EE",
   "merchantId": "PIPE_EE_101",
   "merchantGroup": "Pipedrive"
 },
 {
   "registeredName": "SHUTTERSTOCK, INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@shutterstock.com",
   "phoneNumber": "+16464194452",
   "classification": "Design_Creative_Stock_Media",
   "mccCode": "5968",
   "organizationTin": "TIN-16 Shutterstock",
   "merchantName": "Shutterstock",
   "merchantCity": "New York",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_SHTR_US",
   "merchantId": "SHTR_US_102",
   "merchantGroup": "Shutterstock"
 },
 {
   "registeredName": "SHUTTERSTOCK IRELAND LTD.",
   "countryCode": "IE",
   "currency": "EUR",
   "email": "contact.ie@shutterstock.com",
   "phoneNumber": "+35314823171",
   "classification": "Design_Creative_Stock_Media",
   "mccCode": "5968",
   "organizationTin": "TIN-IE Shutterstock",
   "merchantName": "Shutterstock IE",
   "merchantCity": "Dublin",
   "merchantCountryCode": "IE",
   "acquirerInstitutionId": "ACQ_SHTR_IE",
   "merchantId": "SHTR_IE_103",
   "merchantGroup": "Shutterstock"
 },
 {
   "registeredName": "OFFGAMERS GLOBAL PTE LTD",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@offgamers.com",
   "phoneNumber": "+6531583145",
   "classification": "Other_Services",
   "mccCode": "5816",
   "organizationTin": "TIN-201211029D",
   "merchantName": "OffGamers",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_OFFGM_SG",
   "merchantId": "OFFGM_SG_104",
   "merchantGroup": "OffGamers"
 },
 {
   "registeredName": "ECONOMIST DIGITAL SERVICES LIMITED",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact@economist.com",
   "phoneNumber": "+442078307000",
   "classification": "Publishing_Media_News",
   "mccCode": "5994",
   "organizationTin": "TIN-GB Economist",
   "merchantName": "The Economist",
   "merchantCity": "London",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_ECNMST_GB",
   "merchantId": "ECNMST_GB_105",
   "merchantGroup": "Economist"
 },
 {
   "registeredName": "NATIVE INSTRUMENTS GMBH",
   "countryCode": "DE",
   "currency": "EUR",
   "email": "contact@native-ins.com",
   "phoneNumber": "+49306110350",
   "classification": "Productivity_SaaS",
   "mccCode": "5817",
   "organizationTin": "TIN-DE193 Native",
   "merchantName": "Native Instruments",
   "merchantCity": "Berlin",
   "merchantCountryCode": "DE",
   "acquirerInstitutionId": "ACQ_NATIVE_DE",
   "merchantId": "NATIVE_DE_106",
   "merchantGroup": "Native Inst."
 },
 {
   "registeredName": "UPCLOUD OY",
   "countryCode": "FI",
   "currency": "EUR",
   "email": "contact@upcloud.com",
   "phoneNumber": "+35891234567",
   "classification": "Cloud_IT_Infra",
   "mccCode": "7372",
   "organizationTin": "TIN-FI UpCloud",
   "merchantName": "UpCloud",
   "merchantCity": "Helsinki",
   "merchantCountryCode": "FI",
   "acquirerInstitutionId": "ACQ_UPCLD_FI",
   "merchantId": "UPCLD_FI_107",
   "merchantGroup": "UpCloud"
 },
 {
   "registeredName": "MEGA LIMITED",
   "countryCode": "NZ",
   "currency": "NZD",
   "email": "contact@mega.nz",
   "phoneNumber": "+6491234567",
   "classification": "Streaming_Entertainment",
   "mccCode": "7372",
   "organizationTin": "TIN-NZ Mega",
   "merchantName": "MEGA",
   "merchantCity": "Auckland",
   "merchantCountryCode": "NZ",
   "acquirerInstitutionId": "ACQ_MEGA_NZ",
   "merchantId": "MEGA_NZ_108",
   "merchantGroup": "MEGA"
 },
 {
   "registeredName": "AIRBNB IRELAND UNLIMITED COMPANY",
   "countryCode": "IE",
   "currency": "EUR",
   "email": "contact@airbnb.ie",
   "phoneNumber": "+35316971831",
   "classification": "Travel_Hospitality",
   "mccCode": "4722",
   "organizationTin": "TIN-IE9827385E",
   "merchantName": "Airbnb Ireland",
   "merchantCity": "Dublin",
   "merchantCountryCode": "IE",
   "acquirerInstitutionId": "ACQ_AIRBNB_IE",
   "merchantId": "AIRBNB_IE_109",
   "merchantGroup": "Airbnb"
 },
 {
   "registeredName": "TWITCH INTERACTIVE SINGAPORE PRIVATE LIMITED",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@twitch.sg",
   "phoneNumber": "+6512345678",
   "classification": "Streaming_Entertainment",
   "mccCode": "5815",
   "organizationTin": "TIN-201509358M",
   "merchantName": "Twitch SG",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_TWITCH_SG",
   "merchantId": "TWITCH_SG_110",
   "merchantGroup": "Amazon Global"
 },
 {
   "registeredName": "VONAGE BUSINESS INC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@vonage.com",
   "phoneNumber": "+18662434357",
   "classification": "Financial_Payments",
   "mccCode": "4814",
   "organizationTin": "TIN-Vonage",
   "merchantName": "Vonage",
   "merchantCity": "Holmdel",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_VONAGE_US",
   "merchantId": "VONAGE_US_111",
   "merchantGroup": "Vonage"
 },
 {
   "registeredName": "UDEMY INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@udemy.com",
   "phoneNumber": "+14158131710",
   "classification": "EdTech_Digi_Learn",
   "mccCode": "8299",
   "organizationTin": "TIN-Udemy",
   "merchantName": "Udemy",
   "merchantCity": "San Francisco",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_UDEMY_US",
   "merchantId": "UDEMY_US_112",
   "merchantGroup": "Udemy"
 },
 {
   "registeredName": "ASK.FM EUROPE LIMITED",
   "countryCode": "IE",
   "currency": "EUR",
   "email": "contact@ask.fm",
   "phoneNumber": "+35311234567",
   "classification": "SocMed_Comm",
   "mccCode": "7375",
   "organizationTin": "TIN-IE Ask.fm",
   "merchantName": "Ask.fm",
   "merchantCity": "Dublin",
   "merchantCountryCode": "IE",
   "acquirerInstitutionId": "ACQ_ASKFM_IE",
   "merchantId": "ASKFM_IE_113",
   "merchantGroup": "Ask.fm"
 },
 {
   "registeredName": "HOME BOX OFFICE (SINGAPORE) PTE.LTD.",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@hboasia.com",
   "phoneNumber": "+6563811888",
   "classification": "Streaming_Entertainment",
   "mccCode": "5815",
   "organizationTin": "TIN-199105433W",
   "merchantName": "HBO Asia",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_HBO_SG",
   "merchantId": "HBO_SG_114",
   "merchantGroup": "Warner Bros"
 },
 {
   "registeredName": "IQIYI INTERNATIONAL SINGAPORE PTE. LTD.",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@iq.com",
   "phoneNumber": "+6512345678",
   "classification": "Streaming_Entertainment",
   "mccCode": "5815",
   "organizationTin": "TIN-201914322C",
   "merchantName": "iQIYI SG",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_IQIYI_SG",
   "merchantId": "IQIYI_SG_115",
   "merchantGroup": "Baidu"
 },
 {
   "registeredName": "SPRINGER NATURE CUSTOMER SERVICE CENTER GMBH",
   "countryCode": "DE",
   "currency": "EUR",
   "email": "contact@springer.com",
   "phoneNumber": "+4962214870",
   "classification": "EdTech_Digi_Learn",
   "mccCode": "2741",
   "organizationTin": "TIN-DE Springer",
   "merchantName": "Springer Nature",
   "merchantCity": "Heidelberg",
   "merchantCountryCode": "DE",
   "acquirerInstitutionId": "ACQ_SPRG_DE",
   "merchantId": "SPRG_DE_116",
   "merchantGroup": "Springer"
 },
 {
   "registeredName": "SPRINGER NATURE LIMITED",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact.uk@springer.com",
   "phoneNumber": "+442078364343",
   "classification": "EdTech_Digi_Learn",
   "mccCode": "2741",
   "organizationTin": "TIN-GB Springer",
   "merchantName": "Springer UK",
   "merchantCity": "London",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_SPRG_GB",
   "merchantId": "SPRG_GB_117",
   "merchantGroup": "Springer"
 },
 {
   "registeredName": "PAYPRO EUROPE LIMITED",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact@payproglobal.com",
   "phoneNumber": "+442033973945",
   "classification": "Financial_Payments",
   "mccCode": "6012",
   "organizationTin": "TIN-GB PayPro",
   "merchantName": "PayPro",
   "merchantCity": "London",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_PAYPRO_GB",
   "merchantId": "PAYPRO_GB_118",
   "merchantGroup": "PayPro"
 },
 {
   "registeredName": "JOHN WILEY and SONS, INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@wiley.com",
   "phoneNumber": "+12017486000",
   "classification": "EdTech_Digi_Learn",
   "mccCode": "2741",
   "organizationTin": "TIN-Wiley",
   "merchantName": "Wiley",
   "merchantCity": "Hoboken",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_WILEY_US",
   "merchantId": "WILEY_US_119",
   "merchantGroup": "Wiley"
 },
 {
   "registeredName": "BIOMED CENTRAL LIMITED",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact@biomedcentral.com",
   "phoneNumber": "+442074240300",
   "classification": "EdTech_Digi_Learn",
   "mccCode": "2741",
   "organizationTin": "TIN-GB BioMed",
   "merchantName": "BioMed Central",
   "merchantCity": "London",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_BIOMD_GB",
   "merchantId": "BIOMD_GB_120",
   "merchantGroup": "Springer"
 },
 {
   "registeredName": "COURSERA, INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@coursera.org",
   "phoneNumber": "+18009581701",
   "classification": "EdTech_Digi_Learn",
   "mccCode": "8299",
   "organizationTin": "TIN-Coursera",
   "merchantName": "Coursera",
   "merchantCity": "Mountain View",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_COUR_US",
   "merchantId": "COUR_US_121",
   "merchantGroup": "Coursera"
 },
 {
   "registeredName": "GROUNDHOG TECHNOLOGIES INC.",
   "countryCode": "TW",
   "currency": "TWD",
   "email": "contact@ghtinc.com",
   "phoneNumber": "+886226591000",
   "classification": "Research_Data_Services",
   "mccCode": "4816",
   "organizationTin": "TIN-TW Groundhog",
   "merchantName": "Groundhog Tech",
   "merchantCity": "Taipei",
   "merchantCountryCode": "TW",
   "acquirerInstitutionId": "ACQ_GHT_TW",
   "merchantId": "GHT_TW_123",
   "merchantGroup": "Groundhog"
 },
 {
   "registeredName": "CVMAKER B.V.",
   "countryCode": "NL",
   "currency": "EUR",
   "email": "contact@cvmaker.nl",
   "phoneNumber": "+31851301083",
   "classification": "Productivity_SaaS",
   "mccCode": "8999",
   "organizationTin": "TIN-NL CVmaker",
   "merchantName": "CVmaker",
   "merchantCity": "Eindhoven",
   "merchantCountryCode": "NL",
   "acquirerInstitutionId": "ACQ_CVMAK_NL",
   "merchantId": "CVMAK_NL_124",
   "merchantGroup": "CVmaker"
 },
 {
   "registeredName": "UNIVERSITY OF LONDON",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact@london.ac.uk",
   "phoneNumber": "+442078628000",
   "classification": "EdTech_Digi_Learn",
   "mccCode": "8221",
   "organizationTin": "TIN-GB UoL",
   "merchantName": "Univ. of London",
   "merchantCity": "London",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_UOL_GB",
   "merchantId": "UOL_GB_125",
   "merchantGroup": "UoL"
 },
 {
   "registeredName": "ZENDRIVE INC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@zendrive.com",
   "phoneNumber": "+18559534222",
   "classification": "Productivity_SaaS",
   "mccCode": "4816",
   "organizationTin": "TIN-Zendrive",
   "merchantName": "Zendrive",
   "merchantCity": "San Francisco",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_ZEND_US",
   "merchantId": "ZEND_US_126",
   "merchantGroup": "Zendrive"
 },
 {
   "registeredName": "WAVES INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@waves.com",
   "phoneNumber": "+18659099200",
   "classification": "Other_Services",
   "mccCode": "5817",
   "organizationTin": "TIN-Waves",
   "merchantName": "Waves",
   "merchantCity": "Knoxville",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_WAVES_US",
   "merchantId": "WAVES_US_127",
   "merchantGroup": "Waves"
 },
 {
   "registeredName": "MATCH GROUP, LLC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@match.com",
   "phoneNumber": "+12145763272",
   "classification": "Productivity_SaaS",
   "mccCode": "7299",
   "organizationTin": "TIN-Match",
   "merchantName": "Match.com",
   "merchantCity": "Dallas",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_MATCH_US",
   "merchantId": "MATCH_US_128",
   "merchantGroup": "Match Group"
 },
 {
   "registeredName": "HEWLETT PACKARD INTERNATIONAL SARL",
   "countryCode": "CH",
   "currency": "CHF",
   "email": "contact@hp.com",
   "phoneNumber": "+41587504000",
   "classification": "Cloud_IT_Infra",
   "mccCode": "5045",
   "organizationTin": "TIN-CH HP",
   "merchantName": "HP International",
   "merchantCity": "Meyrin",
   "merchantCountryCode": "CH",
   "acquirerInstitutionId": "ACQ_HP_CH",
   "merchantId": "HP_CH_129",
   "merchantGroup": "HP"
 },
 {
   "registeredName": "ADOBE SYSTEMS SOFTWARE IRELAND LIMITED",
   "countryCode": "IE",
   "currency": "EUR",
   "email": "contact@adobe.ie",
   "phoneNumber": "+35312426700",
   "classification": "Productivity_SaaS",
   "mccCode": "5817",
   "organizationTin": "TIN-IE Adobe",
   "merchantName": "Adobe Ireland",
   "merchantCity": "Dublin",
   "merchantCountryCode": "IE",
   "acquirerInstitutionId": "ACQ_ADOBE_IE",
   "merchantId": "ADOBE_IE_130",
   "merchantGroup": "Adobe"
 },
 {
   "registeredName": "NBA DIGITAL SERVICE INTERNATIONAL, INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@nba.com",
   "phoneNumber": "+12124078000",
   "classification": "Streaming_Entertainment",
   "mccCode": "7941",
   "organizationTin": "TIN-NBA",
   "merchantName": "NBA Digital",
   "merchantCity": "New York",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_NBA_US",
   "merchantId": "NBA_US_131",
   "merchantGroup": "NBA"
 },
 {
   "registeredName": "ALPHA LIT PTE. LTD",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@alphalit.sg",
   "phoneNumber": "+6512345678",
   "classification": "Other_Services",
   "mccCode": "5311",
   "organizationTin": "TIN-SG AlphaLit",
   "merchantName": "Alpha Lit SG",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_ALPHL_SG",
   "merchantId": "ALPHL_SG_132",
   "merchantGroup": "Alpha Lit"
 },
 {
   "registeredName": "COUPA SOFTWARE, INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@coupa.com",
   "phoneNumber": "+16506054600",
   "classification": "Productivity_SaaS",
   "mccCode": "5817",
   "organizationTin": "TIN-Coupa",
   "merchantName": "Coupa",
   "merchantCity": "San Mateo",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_COUPA_US",
   "merchantId": "COUPA_US_133",
   "merchantGroup": "Coupa"
 },
 {
   "registeredName": "ASIAPLAY TAIWAN DIGITAL ENTERTAINMENT LTD",
   "countryCode": "TW",
   "currency": "TWD",
   "email": "contact@asiaplay.tw",
   "phoneNumber": "+88621234567",
   "classification": "Streaming_Entertainment",
   "mccCode": "5816",
   "organizationTin": "TIN-TW Asiaplay",
   "merchantName": "Asiaplay",
   "merchantCity": "Taipei",
   "merchantCountryCode": "TW",
   "acquirerInstitutionId": "ACQ_APLAY_TW",
   "merchantId": "APLAY_TW_134",
   "merchantGroup": "Asiaplay"
 },
 {
   "registeredName": "TAXAMO CHECKOUT LTD",
   "countryCode": "IE",
   "currency": "EUR",
   "email": "contact@taxamo.com",
   "phoneNumber": "+35311234567",
   "classification": "Financial_Payments",
   "mccCode": "6012",
   "organizationTin": "TIN-IE Taxamo",
   "merchantName": "Taxamo",
   "merchantCity": "Kerry",
   "merchantCountryCode": "IE",
   "acquirerInstitutionId": "ACQ_TAXMO_IE",
   "merchantId": "TAXMO_IE_135",
   "merchantGroup": "Vertex"
 },
 {
   "registeredName": "WONDERSHARE GLOBAL LIMITED",
   "countryCode": "HK",
   "currency": "HKD",
   "email": "contact@wondershare.com",
   "phoneNumber": "+85212345678",
   "classification": "Specialized_Software_Tools",
   "mccCode": "5817",
   "organizationTin": "TIN-HK Wondershare",
   "merchantName": "Wondershare",
   "merchantCity": "Hong Kong",
   "merchantCountryCode": "HK",
   "acquirerInstitutionId": "ACQ_WNDR_HK",
   "merchantId": "WNDR_HK_136",
   "merchantGroup": "Wondershare"
 },
 {
   "registeredName": "EPIC GAMES ENTERTAINMENT INTERNATIONAL GMBH",
   "countryCode": "CH",
   "currency": "CHF",
   "email": "contact@epicgames.ch",
   "phoneNumber": "+4112345678",
   "classification": "Streaming_Entertainment",
   "mccCode": "5816",
   "organizationTin": "TIN-CH Epic",
   "merchantName": "Epic Games Intl",
   "merchantCity": "Zug",
   "merchantCountryCode": "CH",
   "acquirerInstitutionId": "ACQ_EPIC_CH",
   "merchantId": "EPIC_CH_137",
   "merchantGroup": "Epic Games"
 },
 {
   "registeredName": "EPIC GAMES COMMERCE GMBH",
   "countryCode": "CH",
   "currency": "CHF",
   "email": "contact.comm@epicgames.ch",
   "phoneNumber": "+4112345678",
   "classification": "Streaming_Entertainment",
   "mccCode": "5816",
   "organizationTin": "TIN-CH Epic Comm",
   "merchantName": "Epic Commerce",
   "merchantCity": "Zug",
   "merchantCountryCode": "CH",
   "acquirerInstitutionId": "ACQ_EPICC_CH",
   "merchantId": "EPICC_CH_138",
   "merchantGroup": "Epic Games"
 },
 {
   "registeredName": "AMAZON ADVERTISING LLC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact.ads@amazon.com",
   "phoneNumber": "+12062661000",
   "classification": "Productivity_SaaS",
   "mccCode": "7311",
   "organizationTin": "TIN-Amazon Ads",
   "merchantName": "Amazon Ads",
   "merchantCity": "Seattle",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_AMZNAD_US",
   "merchantId": "AMZNAD_US_139",
   "merchantGroup": "Amazon Global"
 },
 {
   "registeredName": "AMAZON SERVICES EUROPE S.A.R.L",
   "countryCode": "LU",
   "currency": "EUR",
   "email": "contact@amazon.lu",
   "phoneNumber": "+35226038000",
   "classification": "EComm_Marketplaces",
   "mccCode": "5311",
   "organizationTin": "TIN-LU Amazon EU",
   "merchantName": "Amazon Europe",
   "merchantCity": "Luxembourg",
   "merchantCountryCode": "LU",
   "acquirerInstitutionId": "ACQ_AMZNEU_LU",
   "merchantId": "AMZNEU_LU_140",
   "merchantGroup": "Amazon Global"
 },
 {
   "registeredName": "UNITY TECHNOLOGIES SF",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@unity3d.com",
   "phoneNumber": "+14158941500",
   "classification": "Specialized_Software_Tools",
   "mccCode": "5817",
   "organizationTin": "TIN-Unity",
   "merchantName": "Unity",
   "merchantCity": "San Francisco",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_UNITY_US",
   "merchantId": "UNITY_US_141",
   "merchantGroup": "Unity"
 },
 {
   "registeredName": "UPTODATE INC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@uptodate.com",
   "phoneNumber": "+17813922000",
   "classification": "Productivity_SaaS",
   "mccCode": "8099",
   "organizationTin": "TIN-UpToDate",
   "merchantName": "UpToDate",
   "merchantCity": "Waltham",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_UPTD_US",
   "merchantId": "UPTD_US_142",
   "merchantGroup": "Wolters Kluwer"
 },
 {
   "registeredName": "WPENGINE, INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@wpengine.com",
   "phoneNumber": "+18779736446",
   "classification": "Productivity_SaaS",
   "mccCode": "7372",
   "organizationTin": "TIN-WPEngine",
   "merchantName": "WPEngine",
   "merchantCity": "Austin",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_WPE_US",
   "merchantId": "WPE_US_143",
   "merchantGroup": "WPEngine"
 },
 {
   "registeredName": "AGODA COMPANY PTE LTD",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@agoda.com",
   "phoneNumber": "+6563297500",
   "classification": "Travel_Hospitality",
   "mccCode": "4722",
   "organizationTin": "TIN-200506877R",
   "merchantName": "Agoda",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_AGODA_SG",
   "merchantId": "AGODA_SG_144",
   "merchantGroup": "Booking"
 },
 {
   "registeredName": "SUPERCELL OY",
   "countryCode": "FI",
   "currency": "EUR",
   "email": "contact@supercell.com",
   "phoneNumber": "+358102345678",
   "classification": "Streaming_Entertainment",
   "mccCode": "5816",
   "organizationTin": "TIN-FI Supercell",
   "merchantName": "Supercell",
   "merchantCity": "Helsinki",
   "merchantCountryCode": "FI",
   "acquirerInstitutionId": "ACQ_SPRC_FI",
   "merchantId": "SPRC_FI_145",
   "merchantGroup": "Tencent"
 },
 {
   "registeredName": "TENCENT MUSIC ENTERTAINMENT HONG KONG",
   "countryCode": "HK",
   "currency": "HKD",
   "email": "contact.music@tencent.com",
   "phoneNumber": "+85212345678",
   "classification": "Streaming_Entertainment",
   "mccCode": "5815",
   "organizationTin": "TIN-HK TencentMus",
   "merchantName": "Tencent Music",
   "merchantCity": "Hong Kong",
   "merchantCountryCode": "HK",
   "acquirerInstitutionId": "ACQ_TNCMUS_HK",
   "merchantId": "TNCMUS_HK_146",
   "merchantGroup": "Tencent"
 },
 {
   "registeredName": "HOTJAR LIMITED",
   "countryCode": "MT",
   "currency": "EUR",
   "email": "contact@hotjar.com",
   "phoneNumber": "+35612345678",
   "classification": "Productivity_SaaS",
   "mccCode": "5817",
   "organizationTin": "TIN-MT Hotjar",
   "merchantName": "Hotjar",
   "merchantCity": "St. Julian's",
   "merchantCountryCode": "MT",
   "acquirerInstitutionId": "ACQ_HOTJAR_MT",
   "merchantId": "HOTJAR_MT_147",
   "merchantGroup": "Hotjar"
 },
 {
   "registeredName": "GARMIN (EUROPE) LIMITED",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact@garmin.co.uk",
   "phoneNumber": "+442380524000",
   "classification": "Other_Services",
   "mccCode": "5045",
   "organizationTin": "TIN-GB Garmin",
   "merchantName": "Garmin Europe",
   "merchantCity": "Southampton",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_GARMIN_GB",
   "merchantId": "GARMIN_GB_148",
   "merchantGroup": "Garmin"
 },
 {
   "registeredName": "COREL CORPORATION",
   "countryCode": "CA",
   "currency": "CAD",
   "email": "contact@corel.com",
   "phoneNumber": "+16137288200",
   "classification": "Specialized_Software_Tools",
   "mccCode": "5817",
   "organizationTin": "TIN-CA Corel",
   "merchantName": "Corel",
   "merchantCity": "Ottawa",
   "merchantCountryCode": "CA",
   "acquirerInstitutionId": "ACQ_COREL_CA",
   "merchantId": "COREL_CA_149",
   "merchantGroup": "Alludo"
 },
 {
   "registeredName": "FOXIT SOFTWARE INCORPORATED",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@foxitsoftware.com",
   "phoneNumber": "+15104389090",
   "classification": "Specialized_Software_Tools",
   "mccCode": "5817",
   "organizationTin": "TIN-Foxit",
   "merchantName": "Foxit",
   "merchantCity": "Fremont",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_FOXIT_US",
   "merchantId": "FOXIT_US_150",
   "merchantGroup": "Foxit"
 },
 {
   "registeredName": "TWITCH INTERACTIVE, INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@twitch.tv",
   "phoneNumber": "+14155106100",
   "classification": "Streaming_Entertainment",
   "mccCode": "5815",
   "organizationTin": "TIN-Twitch",
   "merchantName": "Twitch",
   "merchantCity": "San Francisco",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_TWITCH_US",
   "merchantId": "TWITCH_US_152",
   "merchantGroup": "Amazon Global"
 },
 {
   "registeredName": "NCS PEARSON INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@pearson.com",
   "phoneNumber": "+18006277271",
   "classification": "EdTech_Digi_Learn",
   "mccCode": "8299",
   "organizationTin": "TIN-Pearson",
   "merchantName": "Pearson",
   "merchantCity": "Bloomington",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_PEAR_US",
   "merchantId": "PEAR_US_153",
   "merchantGroup": "Pearson"
 },
 {
   "registeredName": "DEEPL SE",
   "countryCode": "DE",
   "currency": "EUR",
   "email": "contact@deepl.com",
   "phoneNumber": "+4922112345678",
   "classification": "Productivity_SaaS",
   "mccCode": "5817",
   "organizationTin": "TIN-DE DeepL",
   "merchantName": "DeepL",
   "merchantCity": "Cologne",
   "merchantCountryCode": "DE",
   "acquirerInstitutionId": "ACQ_DEEPL_DE",
   "merchantId": "DEEPL_DE_154",
   "merchantGroup": "DeepL"
 },
 {
   "registeredName": "SQUARESPACE IRELAND LIMITED",
   "countryCode": "IE",
   "currency": "EUR",
   "email": "contact@squarespace.ie",
   "phoneNumber": "+35319058200",
   "classification": "Productivity_SaaS",
   "mccCode": "7372",
   "organizationTin": "TIN-IE Squarespace",
   "merchantName": "Squarespace IE",
   "merchantCity": "Dublin",
   "merchantCountryCode": "IE",
   "acquirerInstitutionId": "ACQ_SQSP_IE",
   "merchantId": "SQSP_IE_155",
   "merchantGroup": "Squarespace"
 },
 {
   "registeredName": "TRENDSTREAM LTD",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact@globalwebindex.com",
   "phoneNumber": "+442072068300",
   "classification": "Other_Services",
   "mccCode": "8999",
   "organizationTin": "TIN-GB Trendstream",
   "merchantName": "GlobalWebIndex",
   "merchantCity": "London",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_GWI_GB",
   "merchantId": "GWI_GB_156",
   "merchantGroup": "GWI"
 },
 {
   "registeredName": "APTOIDE S.A.",
   "countryCode": "PT",
   "currency": "EUR",
   "email": "contact@aptoide.com",
   "phoneNumber": "+351123456789",
   "classification": "Other_Services",
   "mccCode": "5817",
   "organizationTin": "TIN-PT Aptoide",
   "merchantName": "Aptoide",
   "merchantCity": "Lisbon",
   "merchantCountryCode": "PT",
   "acquirerInstitutionId": "ACQ_APTD_PT",
   "merchantId": "APTD_PT_157",
   "merchantGroup": "Aptoide"
 },
 {
   "registeredName": "NORTONLIFELOCK SINGAPORE PTE LTD",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact.sg@norton.com",
   "phoneNumber": "+6564299900",
   "classification": "Streaming_Entertainment",
   "mccCode": "5817",
   "organizationTin": "TIN-200302302W",
   "merchantName": "NortonLifeLock SG",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_NORT_SG",
   "merchantId": "NORT_SG_158",
   "merchantGroup": "NortonLifeLock"
 },
 {
   "registeredName": "SANDBOX INTERACTIVE GMBH",
   "countryCode": "DE",
   "currency": "EUR",
   "email": "contact@sandbox-int.com",
   "phoneNumber": "+493012345678",
   "classification": "Streaming_Entertainment",
   "mccCode": "5816",
   "organizationTin": "TIN-DE Sandbox",
   "merchantName": "Sandbox Int.",
   "merchantCity": "Berlin",
   "merchantCountryCode": "DE",
   "acquirerInstitutionId": "ACQ_SAND_DE",
   "merchantId": "SAND_DE_159",
   "merchantGroup": "Sandbox"
 },
 {
   "registeredName": "ZWIFT, INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@zwift.com",
   "phoneNumber": "+18554699438",
   "classification": "Health_Fitness_Lifestyle",
   "mccCode": "7997",
   "organizationTin": "TIN-Zwift",
   "merchantName": "Zwift",
   "merchantCity": "Long Beach",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_ZWIFT_US",
   "merchantId": "ZWIFT_US_160",
   "merchantGroup": "Zwift"
 },
 {
   "registeredName": "BLACKLANE GMBH",
   "countryCode": "DE",
   "currency": "EUR",
   "email": "contact@blacklane.com",
   "phoneNumber": "+493020163010",
   "classification": "Other_Services",
   "mccCode": "4121",
   "organizationTin": "TIN-DE Blacklane",
   "merchantName": "Blacklane",
   "merchantCity": "Berlin",
   "merchantCountryCode": "DE",
   "acquirerInstitutionId": "ACQ_BLKLN_DE",
   "merchantId": "BLKLN_DE_162",
   "merchantGroup": "Blacklane"
 },
 {
   "registeredName": "RAZER ONLINE PTE LTD",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@razer.com",
   "phoneNumber": "+6565123456",
   "classification": "EComm_Marketplaces",
   "mccCode": "5045",
   "organizationTin": "TIN-201004198M",
   "merchantName": "Razer",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_RAZER_SG",
   "merchantId": "RAZER_SG_163",
   "merchantGroup": "Razer"
 },
 {
   "registeredName": "SOCIAL ONLINE PAYMENTS LIMITED",
   "countryCode": "IE",
   "currency": "EUR",
   "email": "contact@socialpay.ie",
   "phoneNumber": "+35311234567",
   "classification": "Financial_Payments",
   "mccCode": "6012",
   "organizationTin": "TIN-IE SocialPay",
   "merchantName": "Social Payments",
   "merchantCity": "Dublin",
   "merchantCountryCode": "IE",
   "acquirerInstitutionId": "ACQ_SOCPAY_IE",
   "merchantId": "SOCPAY_IE_164",
   "merchantGroup": "SocialPay"
 },
 {
   "registeredName": "TRADESHIFT HOLDINGS, INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@tradeshift.com",
   "phoneNumber": "+18887018381",
   "classification": "Productivity_SaaS",
   "mccCode": "5817",
   "organizationTin": "TIN-Tradeshift",
   "merchantName": "Tradeshift",
   "merchantCity": "San Francisco",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_TRDS_US",
   "merchantId": "TRDS_US_165",
   "merchantGroup": "Tradeshift"
 },
 {
   "registeredName": "AHREFS PTE. LTD.",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@ahrefs.com",
   "phoneNumber": "+6531584852",
   "classification": "Productivity_SaaS",
   "mccCode": "5817",
   "organizationTin": "TIN-201111674W",
   "merchantName": "Ahrefs",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_AHREFS_SG",
   "merchantId": "AHREFS_SG_166",
   "merchantGroup": "Ahrefs"
 },
 {
   "registeredName": "POSIT SOFTWARE, PBC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@posit.co",
   "phoneNumber": "+18444481212",
   "classification": "Productivity_SaaS",
   "mccCode": "5817",
   "organizationTin": "TIN-Posit",
   "merchantName": "Posit (RStudio)",
   "merchantCity": "Boston",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_POSIT_US",
   "merchantId": "POSIT_US_167",
   "merchantGroup": "Posit"
 },
 {
   "registeredName": "AMAZON EU S.A R.L.",
   "countryCode": "LU",
   "currency": "EUR",
   "email": "contact.eu@amazon.lu",
   "phoneNumber": "+35226038000",
   "classification": "EComm_Marketplaces",
   "mccCode": "5311",
   "organizationTin": "TIN-LU Amazon S.A",
   "merchantName": "Amazon EU",
   "merchantCity": "Luxembourg",
   "merchantCountryCode": "LU",
   "acquirerInstitutionId": "ACQ_AMZNEU_LU2",
   "merchantId": "AMZNEU_LU_168",
   "merchantGroup": "Amazon Global"
 },
 {
   "registeredName": "EVERNOTE CORPORATION",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@evernote.com",
   "phoneNumber": "+16502163700",
   "classification": "Productivity_SaaS",
   "mccCode": "5817",
   "organizationTin": "TIN-Evernote",
   "merchantName": "Evernote US",
   "merchantCity": "Redwood City",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_EVNUS_US",
   "merchantId": "EVNUS_US_169",
   "merchantGroup": "Evernote"
 },
 {
   "registeredName": "LEMON SQUEEZY LLC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@lemonsqueezy.com",
   "phoneNumber": "+18011234567",
   "classification": "Financial_Payments",
   "mccCode": "5311",
   "organizationTin": "TIN-LemonSqueezy",
   "merchantName": "Lemon Squeezy",
   "merchantCity": "Pleasant Grove",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_LMSQ_US",
   "merchantId": "LMSQ_US_170",
   "merchantGroup": "Lemon Squeezy"
 },
 {
   "registeredName": "PT. FINAL IMPIAN NIAGA",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@i-niaga.co.id",
   "phoneNumber": "+622112345678",
   "classification": "EComm_Marketplaces",
   "mccCode": "5311",
   "organizationTin": "TIN-ImpianNiaga",
   "merchantName": "Impian Niaga",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_FIN_SG",
   "merchantId": "FIN_SG_171",
   "merchantGroup": "Impian Niaga"
 },
 {
   "registeredName": "THE WORLD UNIVERSITIES INSIGHTS LIMITED",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact@timeshighered.com",
   "phoneNumber": "+442077823400",
   "classification": "Publishing_Media_News",
   "mccCode": "2741",
   "organizationTin": "TIN-GB WorldUni",
   "merchantName": "Times Higher Ed",
   "merchantCity": "London",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_THE_GB",
   "merchantId": "THE_GB_173",
   "merchantGroup": "Times Higher"
 },
 {
   "registeredName": "CLOUDKEEPER (SINGAPORE) PTE. LTD.",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@cloudkeeper.sg",
   "phoneNumber": "+6512345678",
   "classification": "Cloud_IT_Infra",
   "mccCode": "7372",
   "organizationTin": "TIN-SG CloudKeep",
   "merchantName": "CloudKeeper SG",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_CLDK_SG",
   "merchantId": "CLDK_SG_174",
   "merchantGroup": "CloudKeeper"
 },
 {
   "registeredName": "DFENG LIMITED",
   "countryCode": "HK",
   "currency": "HKD",
   "email": "contact@dfeng.hk",
   "phoneNumber": "+85212345678",
   "classification": "Other_Services",
   "mccCode": "5816",
   "organizationTin": "TIN-HK Dfeng",
   "merchantName": "Dfeng",
   "merchantCity": "Hong Kong",
   "merchantCountryCode": "HK",
   "acquirerInstitutionId": "ACQ_DFENG_HK",
   "merchantId": "DFENG_HK_175",
   "merchantGroup": "Dfeng"
 },
 {
   "registeredName": "OPTIMISE MEDIA (SEA) PTE. LTD.",
   "countryCode": "SG",
   "currency": "SGD",
   "email": "contact@optimisemedia.com",
   "phoneNumber": "+6564084920",
   "classification": "Productivity_SaaS",
   "mccCode": "7311",
   "organizationTin": "TIN-201503732H",
   "merchantName": "Optimise Media",
   "merchantCity": "Singapore",
   "merchantCountryCode": "SG",
   "acquirerInstitutionId": "ACQ_OPTIM_SG",
   "merchantId": "OPTIM_SG_176",
   "merchantGroup": "Optimise Media"
 },
 {
   "registeredName": "FM PRIV LLC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@fastmail.com",
   "phoneNumber": "+12151234567",
   "classification": "Other_Services",
   "mccCode": "5817",
   "organizationTin": "TIN-FM Priv",
   "merchantName": "Fastmail",
   "merchantCity": "Philadelphia",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_FMP_US",
   "merchantId": "FMP_US_177",
   "merchantGroup": "Fastmail"
 },
 {
   "registeredName": "MIDJOURNEY, INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@midjourney.com",
   "phoneNumber": "+14151234567",
   "classification": "Other_Services",
   "mccCode": "5817",
   "organizationTin": "TIN-Midjourney",
   "merchantName": "Midjourney",
   "merchantCity": "San Francisco",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_MDJ_US",
   "merchantId": "MDJ_US_178",
   "merchantGroup": "Midjourney"
 },
 {
   "registeredName": "ARC GAMES INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@arcgames.com",
   "phoneNumber": "+18001234567",
   "classification": "Streaming_Entertainment",
   "mccCode": "5816",
   "organizationTin": "TIN-Arc Games",
   "merchantName": "Arc Games",
   "merchantCity": "Redwood City",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_ARC_US",
   "merchantId": "ARC_US_179",
   "merchantGroup": "Arc Games"
 },
 {
   "registeredName": "DEEZER",
   "countryCode": "FR",
   "currency": "EUR",
   "email": "contact@deezer.com",
   "phoneNumber": "+33184252500",
   "classification": "Streaming_Entertainment",
   "mccCode": "5815",
   "organizationTin": "TIN-FR Deezer",
   "merchantName": "Deezer",
   "merchantCity": "Paris",
   "merchantCountryCode": "FR",
   "acquirerInstitutionId": "ACQ_DEEZER_FR",
   "merchantId": "DEEZER_FR_180",
   "merchantGroup": "Deezer"
 },
 {
   "registeredName": "REBECCA HALL",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact@rebeccahall.co.uk",
   "phoneNumber": "+441234567890",
   "classification": "Other_Services",
   "mccCode": "7922",
   "organizationTin": "TIN-GB RHall",
   "merchantName": "Rebecca Hall",
   "merchantCity": "London",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_RHALL_GB",
   "merchantId": "RHALL_GB_181",
   "merchantGroup": "Individual"
 },
 {
   "registeredName": "YOUZU GAMES HONGKONG LIMITED",
   "countryCode": "HK",
   "currency": "HKD",
   "email": "contact@yoozoo.com",
   "phoneNumber": "+85212345678",
   "classification": "Streaming_Entertainment",
   "mccCode": "5816",
   "organizationTin": "TIN-HK Yoozoo",
   "merchantName": "Yoozoo Games",
   "merchantCity": "Hong Kong",
   "merchantCountryCode": "HK",
   "acquirerInstitutionId": "ACQ_YOOZOO_HK",
   "merchantId": "YOOZOO_HK_182",
   "merchantGroup": "Yoozoo"
 },
 {
   "registeredName": "ARENANET, LLC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@arena.net",
   "phoneNumber": "+14256234300",
   "classification": "Streaming_Entertainment",
   "mccCode": "5816",
   "organizationTin": "TIN-ArenaNet",
   "merchantName": "ArenaNet",
   "merchantCity": "Bellevue",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_ANET_US",
   "merchantId": "ANET_US_183",
   "merchantGroup": "NCSoft"
 },
 {
   "registeredName": "NERIS ANALYTICS LIMITED",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact@16personalities.com",
   "phoneNumber": "+441234567890",
   "classification": "SocMed_Comm",
   "mccCode": "8999",
   "organizationTin": "TIN-GB Neris",
   "merchantName": "16Personalities",
   "merchantCity": "London",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_NERIS_GB",
   "merchantId": "NERIS_GB_184",
   "merchantGroup": "Neris"
 },
 {
   "registeredName": "CIRCLE INTERNET SERVICES, INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@circle.com",
   "phoneNumber": "+18881234567",
   "classification": "Productivity_SaaS",
   "mccCode": "6012",
   "organizationTin": "TIN-Circle",
   "merchantName": "Circle",
   "merchantCity": "Boston",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_CIRCLE_US",
   "merchantId": "CIRCLE_US_185",
   "merchantGroup": "Circle"
 },
 {
   "registeredName": "VIMEO.COM, INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@vimeo.com",
   "phoneNumber": "+12123143300",
   "classification": "Streaming_Entertainment",
   "mccCode": "5815",
   "organizationTin": "TIN-Vimeo",
   "merchantName": "Vimeo",
   "merchantCity": "New York",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_VIMEO_US",
   "merchantId": "VIMEO_US_186",
   "merchantGroup": "Vimeo"
 },
 {
   "registeredName": "TP GLOBAL OPERATIONS LIMITED",
   "countryCode": "CY",
   "currency": "EUR",
   "email": "contact@trading-point.com",
   "phoneNumber": "+35725029933",
   "classification": "Cloud_IT_Infra",
   "mccCode": "6211",
   "organizationTin": "TIN-CY TP Global",
   "merchantName": "Trading Point",
   "merchantCity": "Limassol",
   "merchantCountryCode": "CY",
   "acquirerInstitutionId": "ACQ_TPG_CY",
   "merchantId": "TPG_CY_187",
   "merchantGroup": "Trading Point"
 },
 {
   "registeredName": "BETTERME INTERNATIONAL LIMITED",
   "countryCode": "CY",
   "currency": "EUR",
   "email": "contact@betterme.world",
   "phoneNumber": "+35712345678",
   "classification": "Health_Fitness_Lifestyle",
   "mccCode": "7299",
   "organizationTin": "TIN-CY BetterMe",
   "merchantName": "BetterMe",
   "merchantCity": "Nicosia",
   "merchantCountryCode": "CY",
   "acquirerInstitutionId": "ACQ_BTRME_CY",
   "merchantId": "BTRME_CY_188",
   "merchantGroup": "BetterMe"
 },
 {
   "registeredName": "ACTITECH LIMITED",
   "countryCode": "HK",
   "currency": "HKD",
   "email": "contact@actitech.hk",
   "phoneNumber": "+85212345678",
   "classification": "Health_Fitness_Lifestyle",
   "mccCode": "5045",
   "organizationTin": "TIN-HK Actitech",
   "merchantName": "Actitech",
   "merchantCity": "Hong Kong",
   "merchantCountryCode": "HK",
   "acquirerInstitutionId": "ACQ_ACTI_HK",
   "merchantId": "ACTI_HK_189",
   "merchantGroup": "Actitech"
 },
 {
   "registeredName": "LUMEN RESEARCH LIMITED",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact@lumen-research.com",
   "phoneNumber": "+442078207567",
   "classification": "Research_Data_Services",
   "mccCode": "8999",
   "organizationTin": "TIN-GB Lumen",
   "merchantName": "Lumen Research",
   "merchantCity": "London",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_LUMEN_GB",
   "merchantId": "LUMEN_GB_191",
   "merchantGroup": "Lumen"
 },
 {
   "registeredName": "AMAZON JAPAN G.K.",
   "countryCode": "JP",
   "currency": "JPY",
   "email": "contact@amazon.co.jp",
   "phoneNumber": "+81363674500",
   "classification": "EComm_Marketplaces",
   "mccCode": "5311",
   "organizationTin": "TIN-JP Amazon",
   "merchantName": "Amazon Japan",
   "merchantCity": "Tokyo",
   "merchantCountryCode": "JP",
   "acquirerInstitutionId": "ACQ_AMZN_JP",
   "merchantId": "AMZN_JP_192",
   "merchantGroup": "Amazon Global"
 },
 {
   "registeredName": "VORWERK INTERNATIONAL and CO. KMG",
   "countryCode": "CH",
   "currency": "CHF",
   "email": "contact@vorwerk.com",
   "phoneNumber": "+41447869797",
   "classification": "Cloud_IT_Infra",
   "mccCode": "5722",
   "organizationTin": "TIN-CH Vorwerk",
   "merchantName": "Vorwerk Intl",
   "merchantCity": "Wollerau",
   "merchantCountryCode": "CH",
   "acquirerInstitutionId": "ACQ_VORW_CH",
   "merchantId": "VORW_CH_193",
   "merchantGroup": "Vorwerk"
 },
 {
   "registeredName": "HUAWEI SERVICE (HONG KONG) CO., LIMITED",
   "countryCode": "HK",
   "currency": "HKD",
   "email": "contact@huawei.com",
   "phoneNumber": "+85229062300",
   "classification": "Productivity_SaaS",
   "mccCode": "5045",
   "organizationTin": "TIN-HK Huawei",
   "merchantName": "Huawei Service HK",
   "merchantCity": "Hong Kong",
   "merchantCountryCode": "HK",
   "acquirerInstitutionId": "ACQ_HUAW_HK",
   "merchantId": "HUAW_HK_194",
   "merchantGroup": "Huawei"
 },
 {
   "registeredName": "SOUNDS TRUE INC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@soundstrue.com",
   "phoneNumber": "+18003339185",
   "classification": "Publishing_Media_News",
   "mccCode": "2741",
   "organizationTin": "TIN-SoundsTrue",
   "merchantName": "Sounds True",
   "merchantCity": "Louisville",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_SNDTR_US",
   "merchantId": "SNDTR_US_195",
   "merchantGroup": "Sounds True"
 },
 {
   "registeredName": "SITEGROUND HOSTING LTD.",
   "countryCode": "BG",
   "currency": "EUR",
   "email": "contact@siteground.com",
   "phoneNumber": "+18008289231",
   "classification": "Cloud_IT_Infra",
   "mccCode": "7372",
   "organizationTin": "TIN-BG SiteGround",
   "merchantName": "SiteGround",
   "merchantCity": "Sofia",
   "merchantCountryCode": "BG",
   "acquirerInstitutionId": "ACQ_STGR_BG",
   "merchantId": "STGR_BG_196",
   "merchantGroup": "SiteGround"
 },
 {
   "registeredName": "BROWSERSTACK INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@browserstack.com",
   "phoneNumber": "+18557552528",
   "classification": "Cloud_IT_Infra",
   "mccCode": "5817",
   "organizationTin": "TIN-BrowserStack",
   "merchantName": "BrowserStack",
   "merchantCity": "San Francisco",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_BRST_US",
   "merchantId": "BRST_US_197",
   "merchantGroup": "BrowserStack"
 },
 {
   "registeredName": "TOTAL SECURITY LIMITED",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact@totalav.com",
   "phoneNumber": "+448000119586",
   "classification": "Security_VPN_Privacy",
   "mccCode": "5817",
   "organizationTin": "TIN-GB TotalSec",
   "merchantName": "TotalAV",
   "merchantCity": "Fareham",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_TOTAV_GB",
   "merchantId": "TOTAV_GB_198",
   "merchantGroup": "TotalAV"
 },
 {
   "registeredName": "PEARSON EDUCATION LIMITED",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact.uk@pearson.com",
   "phoneNumber": "+442070102000",
   "classification": "EdTech_Digi_Learn",
   "mccCode": "8299",
   "organizationTin": "TIN-GB Pearson",
   "merchantName": "Pearson UK",
   "merchantCity": "London",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_PEAR_GB",
   "merchantId": "PEAR_GB_199",
   "merchantGroup": "Pearson"
 },
 {
   "registeredName": "TRAVIAN GAMES GMBH",
   "countryCode": "DE",
   "currency": "EUR",
   "email": "contact@traviangames.com",
   "phoneNumber": "+498932491590",
   "classification": "Streaming_Entertainment",
   "mccCode": "5816",
   "organizationTin": "TIN-DE Travian",
   "merchantName": "Travian Games",
   "merchantCity": "Munich",
   "merchantCountryCode": "DE",
   "acquirerInstitutionId": "ACQ_TRVN_DE",
   "merchantId": "TRVN_DE_200",
   "merchantGroup": "Travian"
 },
 {
   "registeredName": "GETYOURGUIDE DEUTSCHLAND GMBH",
   "countryCode": "DE",
   "currency": "EUR",
   "email": "contact@getyourguide.com",
   "phoneNumber": "+493054445944",
   "classification": "EComm_Marketplaces",
   "mccCode": "4722",
   "organizationTin": "TIN-DE GetYourGuide",
   "merchantName": "GetYourGuide",
   "merchantCity": "Berlin",
   "merchantCountryCode": "DE",
   "acquirerInstitutionId": "ACQ_GYG_DE",
   "merchantId": "GYG_DE_201",
   "merchantGroup": "GetYourGuide"
 },
 {
   "registeredName": "GW SOLUTIONS LTD",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact@gw-solutions.co.uk",
   "phoneNumber": "+441234567890",
   "classification": "Other_Services",
   "mccCode": "7379",
   "organizationTin": "TIN-GB GW Sol",
   "merchantName": "GW Solutions",
   "merchantCity": "London",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_GWS_GB",
   "merchantId": "GWS_GB_202",
   "merchantGroup": "GW Solutions"
 },
 {
   "registeredName": "SERVICIOS COMERCIALES AMAZON MEXICO, S. DE R.L. DE C.V.",
   "countryCode": "MX",
   "currency": "MXN",
   "email": "contact@amazon.com.mx",
   "phoneNumber": "+525512345678",
   "classification": "EComm_Marketplaces",
   "mccCode": "5311",
   "organizationTin": "TIN-MX Amazon",
   "merchantName": "Amazon Mexico",
   "merchantCity": "Mexico City",
   "merchantCountryCode": "MX",
   "acquirerInstitutionId": "ACQ_AMZN_MX",
   "merchantId": "AMZN_MX_203",
   "merchantGroup": "Amazon Global"
 },
 {
   "registeredName": "1GLOBAL OPERATIONS (NETHERLANDS) BV",
   "countryCode": "NL",
   "currency": "EUR",
   "email": "contact@1global.com",
   "phoneNumber": "+31123456789",
   "classification": "Other_Services",
   "mccCode": "4814",
   "organizationTin": "TIN-NL 1Global",
   "merchantName": "1Global",
   "merchantCity": "Amsterdam",
   "merchantCountryCode": "NL",
   "acquirerInstitutionId": "ACQ_1GLBL_NL",
   "merchantId": "1GLBL_NL_204",
   "merchantGroup": "1Global"
 },
 {
   "registeredName": "WARGAMING GROUP LIMITED",
   "countryCode": "CY",
   "currency": "EUR",
   "email": "contact@wargaming.net",
   "phoneNumber": "+35722864444",
   "classification": "Streaming_Entertainment",
   "mccCode": "5816",
   "organizationTin": "TIN-CY Wargaming",
   "merchantName": "Wargaming",
   "merchantCity": "Nicosia",
   "merchantCountryCode": "CY",
   "acquirerInstitutionId": "ACQ_WARG_CY",
   "merchantId": "WARG_CY_205",
   "merchantGroup": "Wargaming"
 },
 {
   "registeredName": "STUDEERSNEL B.V.",
   "countryCode": "NL",
   "currency": "EUR",
   "email": "contact@studeersnel.nl",
   "phoneNumber": "+31123456789",
   "classification": "Publishing_Media_News",
   "mccCode": "8299",
   "organizationTin": "TIN-NL Studeer",
   "merchantName": "StudeerSnel",
   "merchantCity": "Amsterdam",
   "merchantCountryCode": "NL",
   "acquirerInstitutionId": "ACQ_STDR_NL",
   "merchantId": "STDR_NL_206",
   "merchantGroup": "StuDocu"
 },
 {
   "registeredName": "JUSTANSWER LLC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@justanswer.com",
   "phoneNumber": "+18005095721",
   "classification": "Productivity_SaaS",
   "mccCode": "8999",
   "organizationTin": "TIN-JustAnswer",
   "merchantName": "JustAnswer",
   "merchantCity": "San Francisco",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_JSTANS_US",
   "merchantId": "JSTANS_US_207",
   "merchantGroup": "JustAnswer"
 },
 {
   "registeredName": "TRELLO INC.,",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@trello.com",
   "phoneNumber": "+18001234567",
   "classification": "Other_Services",
   "mccCode": "5817",
   "organizationTin": "TIN-Trello",
   "merchantName": "Trello",
   "merchantCity": "New York",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_TRELLO_US",
   "merchantId": "TRELLO_US_208",
   "merchantGroup": "Atlassian"
 },
 {
   "registeredName": "REALTIMEBOARD INC.",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@miro.com",
   "phoneNumber": "+18881234567",
   "classification": "Productivity_SaaS",
   "mccCode": "5817",
   "organizationTin": "TIN-Miro",
   "merchantName": "Miro",
   "merchantCity": "San Francisco",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_MIRO_US",
   "merchantId": "MIRO_US_209",
   "merchantGroup": "Miro"
 },
 {
   "registeredName": "PLUGIN BOUTIQUE LIMITED",
   "countryCode": "GB",
   "currency": "GBP",
   "email": "contact@pluginboutique.com",
   "phoneNumber": "+441234567890",
   "classification": "Gaming_Platforms_Distribution",
   "mccCode": "5817",
   "organizationTin": "TIN-GB Plugin",
   "merchantName": "Plugin Boutique",
   "merchantCity": "London",
   "merchantCountryCode": "GB",
   "acquirerInstitutionId": "ACQ_PLGN_GB",
   "merchantId": "PLGN_GB_210",
   "merchantGroup": "Plugin Boutique"
 },
 {
   "registeredName": "KAJABI LLC",
   "countryCode": "US",
   "currency": "USD",
   "email": "contact@kajabi.com",
   "phoneNumber": "+18001234567",
   "classification": "Productivity_SaaS",
   "mccCode": "5817",
   "organizationTin": "TIN-Kajabi",
   "merchantName": "Kajabi",
   "merchantCity": "Irvine",
   "merchantCountryCode": "US",
   "acquirerInstitutionId": "ACQ_KAJABI_US",
   "merchantId": "KAJABI_US_211",
   "merchantGroup": "Kajabi"
 }
]